### ISSUE TITLE
Analyze production mainnet service memory usage

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1008]
**Describe the bug**
- Production mainnet service uses a lot of memory (around 18Gb an peaks of 30Gb with 4 instances, so 4.5Gb and peaks of 7.5Gb per instance). Instances are controlled by gunicorn `WEB_CONCURRENCY` variable: https://docs.gunicorn.org/en/stable/settings.html#workers . On production `WEB_CONCURRENCY=4`
- We need to check if that's a good usage of the memory or there's some leak or part where it's not needed to spend so much.

**To Reproduce**
- Check Grafana for Mainnet Transaction Service on production
![image](https://user-images.githubusercontent.com/6909403/183076058-0bcd8843-68a0-47d9-93ce-9fb9b6f39fb9.png)

**Expected behavior**
- Not clear of the reasonable usage for the service.
- Our objective should be to know if the service is making a reasonable usage of the memory.

**Proposed solutions**
 - Check `@cached`, `@cached_property`, etc. that store information locally without limit and not on Redis (e.g. `cache_page` uses Redis if everything is well configured).
 - Check parts of the code where we can be manually store data and not releasing.
 - We should try to store everything cached on Redis unless it's something small that brings good speedup (e.g. storing eth current USD value).
 - Reduce `WEB_CONCURRENCY` and increase `gevent workers` (currently 2,000 but it should support way more)
 - Set `WEB_CONCURRENCY=4` on staging and test.

**Comment by moisses89** [comment]
This could be an example of memory cached locally:
   ```
 @cachedmethod(cache=operator.attrgetter("cache_uri_metadata"))
    @cache_memoize(
        60 * 60 * 24,
        prefix="collectibles-_retrieve_metadata_from_uri",
        cache_exceptions=(MetadataRetrievalException,),
    )  # 1 day
    def _retrieve_metadata_from_uri(self, uri: str) -> Any:
```
And cached for 1 day.

**Comment by moisses89** [comment]
> This could be an example of memory cached locally:
> 
> ```
> @cachedmethod(cache=operator.attrgetter("cache_uri_metadata"))
>  @cache_memoize(
>      60 * 60 * 24,
>      prefix="collectibles-_retrieve_metadata_from_uri",
>      cache_exceptions=(MetadataRetrievalException,),
>  )  # 1 day
>  def _retrieve_metadata_from_uri(self, uri: str) -> Any:
> ```
> 
> And cached for 1 day.
There is not an issue here because has defined maxsize to 4096
```
maxsize=4096
```

**Comment by moisses89** [comment]
Trying each endpoint I found that every time that I get safe information from the api the memory usage is increasing.   
Then I could check that the issue is not in transaction-service code, it is in safe-eth-py library. 
```
    @cache
    def get_contract(self) -> Contract:
        v_1_3_0_contract = get_safe_V1_3_0_contract(self.w3, address=self.address)
        version = v_1_3_0_contract.functions.VERSION().call()
        if version == "1.3.0":
            return v_1_3_0_contract
        else:
            return get_safe_V1_1_1_contract(self.w3, address=self.address)
```
Removing this cache without limit in time and in size the transaction service reduce considerably the memory usage.

**Comment by moisses89** [comment]
To add more information related how is incrementing the memory this function I did a comparative with caching on `get_contract` and without caching. 
Then I did 500 requests without any change (with caching):
![gunicorn_210153(1)](https://user-images.githubusercontent.com/7888669/183906233-edd192c5-4b18-48c8-a27d-e326de9d504c.png)
And then restarted the process and the same without caching:
![gunicorn_209431](https://user-images.githubusercontent.com/7888669/183906297-5b296a96-b3ac-45fc-8e4c-d559ab679b4f.png)

Without caching the process reach 136MB and stops his increment, with caching the other process is incrementing continuously without stop.
