### ISSUE TITLE
Goerli indexer stuck but node seems to be indexing

### ISSUE THREAD

**Issue by fmrsabino** [safe-global/safe-transaction-service#1039]
Our Goerli node seems to be syncing correctly (see https://safe-transaction.goerli.gnosis.io/api/v1/about/ethereum-tracing-rpc/)

However the indexer seems to be stuck (or moving really slowly) see – https://safe-transaction.goerli.gnosis.io/api/v1/about/master-copies/

We should check if there's any issue that causes this big difference in our indexing.

**Comment by Uxio0** [comment]
Looks like we were using the wrong node. Service looks up to date now
