### ISSUE TITLE
Changes for "The Merge"

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1059]
# What is needed?
Do certain changes after **The Merge**:
- Rename `latest` RPC calls to `unsafe` (or maybe `safe`)
 
# Background
https://blog.infura.io/post/what-you-need-to-know-to-get-ready-for-the-ethereum-merge-infura-developers-edition

**Comment by moisses89** [comment]
@Uxio0 Could we close this issue?

**Comment by Uxio0** [comment]
> @Uxio0 Could we close this issue?

Not really sure, we must investigate if those changes were applied at last. Could you check?

**Comment by moisses89** [comment]
@Uxio0 following the document, after merge the changes are related with PoW parameters. 
Transaction-service model doesn't store this information but we have some mock files for testing that is mocking this values:
- nonce -> 0
- difficulty -> 0
After review transaction-service code, I can see that there are only mock files that have difficulty different to 0, I'm going to do a PR to fix it.

**Comment by Uxio0** [comment]
Could it be that the mocks are from PoW blocks?

**Comment by Uxio0** [comment]
Yes
