### ISSUE TITLE
Public mainnet safe client returns 404 for a valid Gnosis safe address

### ISSUE THREAD

**Issue by stewart-prysm** [safe-global/safe-transaction-service#1064]
**Describe the bug**
I'm using the gnosis safe SDK client to estimate gas. For this particular safe 0x84C3B816526afC3f16dfD53cB238ab91229051FD, the estimations endpoint https://safe-transaction.gnosis.io/api/v1/safes/0x84C3B816526afC3f16dfD53cB238ab91229051FD/multisig-transactions/estimations/ returns a 404.

I also noticed that the gnosis safe webapp is unable to load this safe https://gnosis-safe.io/app/load, giving this error: Address given is not a valid Safe address.

This safe was created through the prysm.xyz app in this transaction https://etherscan.io/tx/0xf5fbec773eae0c35a6bb5208548c8c012ee65d94dac2cc9fc5caf809202138f1

**To Reproduce**

```
curl -i 'https://safe-transaction.gnosis.io/api/v1/safes/0x84C3B816526afC3f16dfD53cB238ab91229051FD/multisig-transactions/estimations/' \
  -H 'Accept: application/json' \
  --data-raw '{"to":"0x05BbBfa5e08B3716d38e0a77EbbF092D000b9Bd8","value":"0","data":"0x42842e0e00000000000000000000000084c3b816526afc3f16dfd53cb238ab91229051fd000000000000000000000000725c8e68c2d11cf96a97ce96bf8533169dd5bc2a000000000000000000000000000000000000000000000000000000000000040e","operation":0}' \
  --compressed
```
This returns a 404 which is not expected.

**Expected behavior**
A 200 status with gas estimation is returned.

**Environment (please complete the following information):**
 - Production
 - mainnet
 - OS: NA
 - Browser - all
 - Version - NA

**Additional context**
I'm unable to reproduce this in other cases-- I can create a safe on prysm.xyz, estimate gas, and load on the gnosis safe webapp. This is a one-off issue for this safe only-- I cannot reproduce with other safes. It seems that the gnosis safe infrastructure has not indexed this particular safe maybe? Any help would be appreciated! This has "bricked" a customer's safe. They cannot withdraw any NFTs they transferred into this safe, both in the prysm UI and the gnosis safe web app UI because any use of the safe service returns a 404 for this safe..

**Comment by fmrsabino** [comment]
@stewart-prysm there was an issue with indexing. Your Safe should show up now in the interface and the estimation call should work now too.

**Comment by Uxio0** [comment]
I can confirm it's working now https://safe-transaction.gnosis.io/api/v1/safes/0x84C3B816526afC3f16dfD53cB238ab91229051FD/
