### ISSUE TITLE
Failed to fetch data from admin panel UI

### ISSUE THREAD

**Issue by t3dkich** [safe-global/safe-transaction-service#1097]
**Describe the bug**
I ran a local server on http://localhost:8000, logged in as admin. When I try to execute some request from UI - for instance "http://localhost/api/v1/about/" - get error 
```
Failed to fetch.
Possible Reasons:
  - CORS
  - Network Failure
  - URL scheme must be "http" or "https" for CORS request.
```
then tried "http://localhost:8000/api/v1/about/" in the browser url bar - got the successful response info as it's supposed to be.

Are there some settings that I need to do?

**Environment (please complete the following information):**
 - .env local
 - Private chain
 - OS: MacOs
 - Browser Brave

**Comment by Uxio0** [comment]
Take a look on https://github.com/safe-global/safe-infrastructure for configuration examples
