### ISSUE TITLE
Enable/disable oracles on price_service 

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1105]
# What is needed?
I would like to have the option to enable or disable oracles on `PriceService.enabled_price_oracles`

# Background
Currently we are returning the first price from the first oracle that returns a value. This means if the oracle is returning a wrong value and the other oracles have the correct one we are going to return the wrong. 
I think if we aware that there is an issue on the oracle pool we could disable it, to avoid return wrong results. 

# Related issues
Some wrong prices from some oracles-

**Comment by moisses89** [comment]
From this PR https://github.com/safe-global/safe-eth-py/pull/367 we didn't receive any issue with wrong price for any token, that means that the issue with the oracle pool was the liquidity. 
I'd say to change the priority to low for this issue. @Uxio0

**Comment by Uxio0** [comment]
Price features will be discontinued so this is not relevant anymore. We will only do maintenance for price related features.
