### ISSUE TITLE
Failed to load static resources after docker-compose up

### ISSUE THREAD

**Issue by mhxw** [safe-global/safe-transaction-service#1113]
**Describe the bug**
After docker-compose up, access to static resources on port 8000 is successful, and access to static resources on port 8888 fails. http://ip:8000 login prompt:Forbidden (403),port 8888 can login successfully, but static resources are not displayed. After setting CSRF_TRUSTED_ORIGINS did not have an effect on the above problem.

**To Reproduce**
1. setup and deploy

```
cp .env.l2.sample .env
docker-compose build --force-rm
docker-compose up
docker exec -it safe-transaction-service-web-1 python manage.py createsuperuser
```
2. login

- **http://ip:8000** :access to static resources success, login prompt:Forbidden (403) CSRF verification failed. Request aborted.
-  **http://ip:8888** :access to static resources fail, login success.

3. set `CSRF_TRUSTED_ORIGINS` to .env

```CSRF_TRUSTED_ORIGINS=["https://.example.com","http://ip:8000"]```

No. 2 problems still exist.

**Environment (please complete the following information):**
 - Version [v4.10.2]

**Comment by Hcreak** [comment]
I had this problem too I found django's CSRF sucks

**Comment by mhxw** [comment]
> I had this problem too I found django's CSRF sucks

Is there any solution?

**Comment by Uxio0** [comment]
I know this issue is older but I've just answered here: https://github.com/safe-global/safe-transaction-service/issues/1113
