### ISSUE TITLE
NFT image is not propagated to the service if encoded as data URI scheme

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/safe-transaction-service#1149]
**Describe the bug**
If an NFT encodes the metadata as a data URI scheme which includes the image encoded as a data URI scheme as well, the image is not available in the interface.

**To Reproduce**
Steps to reproduce the behaviour:
1. Send a GET request to https://safe-transaction-goerli.safe.global/api/v1/safes/0xCDd6e79fBC90643dC59273500E3A408EfA24d57C/collectibles/?trusted=false&exclude_spam=false
2. The image URL points to a non-existing resource https://safe-transaction-assets.safe.global/tokens/logos/0xBe41D6b67D1796A7196f08f43165724E196C15F1.png)

**Expected behavior**dec
The image is parsed from the metadata and added to the service

**Environment (please complete the following information):**
 - Production
 - Goerli
 - OS: Symbian
 - Chrome

**Additional context**
Decoded token metadata from base64:
[decoded_metadata.txt](https://github.com/safe-global/safe-transaction-service/files/9927180/decoded_metadata.txt)

Data URI scheme RFC: https://datatracker.ietf.org/doc/html/rfc2397

**Comment by jfschwarz** [comment]
Also the name from the metadata (`"SPROUTING VAPOROUS HEAVENS"` in this example) does not seem to be taken into account

**Comment by yagopv** [comment]
There is a support ticket related to this => https://github.com/5afe/safe-support/issues/43

**Comment by Uxio0** [comment]
I've just created a PR for this: https://github.com/safe-global/safe-transaction-service/pull/1305

**Comment by mikhailxyz** [comment]
legend @Uxio0

**Comment by liliya-soroka** [comment]
web-core ticket - https://github.com/safe-global/safe-ios/issues/2897
