### ISSUE TITLE
Non Owner addresses can execute multi.sig TXs

### ISSUE THREAD

**Issue by JoPark20** [safe-global/safe-transaction-service#1155]
Dear Safe Team,
today I have hit a (possible) bug when using Gnosis safe on my Laptop on Arbitrum.
Let me try to explain it:
I was able to execute a 3-6 Multisig transaction, while the address which executed the TX was not an owner of the multi-sig.
The TX: https://arbiscan.io/tx/0xa00e454cf360c2f6539b75453f423e2bb546b8bc8e6abffc89dd5b4524fb182e
The Multisig: https://gnosis-safe.io/app/arb1:0xB9eBe487fc454264CbCdDfd19374D4D2353c779d

**To Reproduce**
1. Have a 3-6 Multisig on ARB
2. Create a TX
3. Let it sign by two other people
4. Execute the TX with an address which is NOT an owner

**Environment (please complete the following information):**
- Production
- Edge Browser
- Windows 10
- latest Safe version

**Additional context**
What's worth mentioning is, that the 0x842.. address was once an owner of this treasury, but was changed several months ago. 
So there is not really a security risk here, as at least 3 people of the multisig signers had to sign the TX before it can be executed. 

**Expected behavior**
Yet I doesn't feel nice that an outside address can execute such Transactions, as I had expected that you can't execute a TX without being an owner of the safe. 

I'm happy to provide more info if you need any. 

With kind regards, 
Joe

**Comment by 0u8120u812** [comment]
I believe any address can execute a transaction as long as minimum number of SAFE owners that own a SAFE approve a transaction before execution. (M-Of-N is met).

**Comment by JoPark20** [comment]
Okay - I wasn't aware of this, thanks.
Will close the issue.
