### ISSUE TITLE
Add abi for goerli testnet: 0x48b7264e1B334b0A807e2b403597B2715a3a45cd

### ISSUE THREAD

**Issue by CanvasL** [safe-global/safe-transaction-service#1161]
[{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint256","name":"term","type":"uint256"}],"name":"getDepositWeight","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function","constant":true},{"inputs":[{"internalType":"address","name":"tokenAddress","type":"address"},{"internalType":"uint256","name":"loanTerm","type":"uint256"},{"internalType":"uint256","name":"maxLoanTerm","type":"uint256"}],"name":"getLoanInterestRate","outputs":[{"internalType":"uint256","name":"loanInterestRate","type":"uint256"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[{"internalType":"address","name":"tokenAddress","type":"address"}],"name":"getAllRates","outputs":[{"internalType":"uint256[]","name":"termList","type":"uint256[]"},{"internalType":"uint256[]","name":"interestRateList","type":"uint256[]"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[{"internalType":"address","name":"tokenAddress","type":"address"},{"internalType":"uint256[]","name":"loanTerms","type":"uint256[]"},{"internalType":"uint256[]","name":"loanInterestRates","type":"uint256[]"}],"name":"setRates","outputs":[],"stateMutability":"nonpayable","type":"function"}]

**Comment by Uxio0** [comment]
Verify your contract on Sourcify an Etherscan if you want to see it on the service
