### ISSUE TITLE
Measure blocks indexed per second

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-transaction-service#1214]
# What is needed?
On each indexer task run, publish an event to Datadog containing both the network, the blocks indexed, and the duration of the task execution. This way we can extract a metric to monitor the block indexing rate for each network.

# Background
[Datadog custom events](https://docs.datadoghq.com/metrics/custom_metrics/dogstatsd_metrics_submission/#count)

**Comment by moisses89** [comment]
@hectorgomezv the number of blocks per second could be calculated using the task result after this PR https://github.com/safe-global/safe-transaction-service/pull/1328
