### ISSUE TITLE
Can not login `http://localhost:8000/admin/`

### ISSUE THREAD

**Issue by gzliudan** [safe-global/safe-transaction-service#1225]
**Describe the bug**
Admin can not login web site after startup.

**To Reproduce**
1) Setup
```shell
git clone https://github.com/safe-global/safe-transaction-service.git
cd safe-transaction-service/
python -m venv venv
source venv/bin/activate
pip install -r requirements-dev.txt
pre-commit install -f
```

2) Create .env
```shell
cp .env.l2.sample .env
echo 'CSRF_TRUSTED_ORIGINS=["http://localhost:8000","http://127.0.0.1:8000","http://localhost:8888","http://127.0.0.1:8888"]' >> .env
```

3) Startup
```shell
docker compose build --force-rm
docker compose up
```

4) Create admin
```shell
docker exec -it safe-transaction-service-web-1 python manage.py createsuperuser
```

5) Login
Open URL `http://localhost:8000/admin` and login as admin, below is error messages:
![1670901944410](https://user-images.githubusercontent.com/7695325/207219170-c07c2942-ca10-46b7-90f4-311b7d15b728.png)

**Expected behavior**
Should login OK.

**Environment (please complete the following information):**
 - OS:  Ubuntu 22.04.1 LTS
 - Browser FireFox v107.0.1

**Additional context**

Can not login http://localhost:8888/ also after clikc `Django Login` :
![1670902236414](https://user-images.githubusercontent.com/7695325/207219798-d6cbbe1a-7d50-46f0-b280-494fc5e4b301.png)

![1670902261133](https://user-images.githubusercontent.com/7695325/207219849-37ecc309-db35-41d6-ad6d-beaf1527f18c.png)

**Comment by Uxio0** [comment]
I think `echo 'CSRF_TRUSTED_ORIGINS=["http://localhost:8000","http://127.0.0.1:8000","http://localhost:8888","http://127.0.0.1:8888"]' >> .env` should be `echo 'CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000,http://localhost:8888,http://127.0.0.1:8888' >> .env`

**Comment by Uxio0** [comment]
Also you should be using http://localhost:8000/admin and not http://localhost:8888

**Comment by gzliudan** [comment]
Thanks, I will test again tomorrow.

**Comment by Uxio0** [comment]
I've just checked, it's working for me

**Comment by gzliudan** [comment]
The problem is resolved. Thank you again. Maybe the documents need some upodate.

**Comment by Uxio0** [comment]
Thank you very much. You are right, we need to improve our docs
