### ISSUE TITLE
Invalidate Safe related data when a SafeMessage is created/updated

### ISSUE THREAD

**Issue by fmrsabino** [safe-global/safe-transaction-service#1240]
# What is needed?
Trigger the cache invalidation hook whenever a `safe_messages.models.SafeMessage` is modified/created.

# Background
The endpoint `GET /v1/chains/<chain_id>/safes/<safe_address>` on the Safe Client Gateway gets the latest modified message via the Safe Transaction Service endpoint: `GET /v1/safes/{}/messages/?ordering=-modified&limit=1`. This works quite well however when the Safe Client Gateway returns the response to the clients the resulting message is cached (for 1 hour).

Even if the Safe gets new messages (or any other message is updated), the Safe Info cache is not invalidated and the the current stored payload is returned.

# Related issues
- https://github.com/safe-global/web-core/issues/1403

**Comment by moisses89** [comment]
@fmrsabino I would like to confirm the payloads for each type of webhook. 
When a new message is created: 
{
 "address": "safe_address",
  "type": "MESSAGE_CREATED", 
  "message_hash": "hash"
}
When a confirmation is added: 
{
 "address": "safe_address",
  "type": "MESSAGE_CONFIRMATION", 
  "message_hash": "hash"
}
It is ok for you or I'm missing something?
