### ISSUE TITLE
Origin field not returning valid JSON

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1244]
**Describe the bug**
`origin` field for `MultisigTransaction` is not returning a valid JSON.

**To Reproduce**
Check https://safe-transaction-goerli.safe.global/api/v1/multisig-transactions/0x86409c1fcbe3638976bd1d4e644a6112c137b007f1969a4915820f8d2307a1a7/

```
"origin": "{'url': 'https://random-safe.app', 'name': 'Random Safe App', 'origin': 'integration-test'}",
```

**Expected behavior**
```
"origin": "{\\"url\\": \\"https://random-safe.app\\", \\"name\\": \\"Random Safe App\\", \\"origin\\": \\"integration-test\\"}"",
```

**Environment (please complete the following information):**
 - Production
 - Every chain

**Comment by Uxio0** [comment]
@safe-global/safe-web @dasanra (I didn't find a sapps handle), I'm surprised this is not breaking anything for you

**Comment by mikhailxyz** [comment]
@Uxio0 I think we never expected it to be valid because IIRC we used to have a character size limit for this field. So if an app had a large enough name + url, you'd get only half of it, lol.

**Comment by moisses89** [comment]
I think the expected should be gotten locally from version `v4.12.2` before origin change:
`"origin": "{\"name\":\"$SAFE Claiming App\",\"url\":\"https://safe-apps.dev.safe.global/safe-claiming-app\"}"`
