### ISSUE TITLE
Analyze webhooks/invalidation on owners removal

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-transaction-service#1253]
# What is needed?
Analysis of a potential bug in a user flow where a queued transaction info returned by the Client Gateway is incorrect after one of the signers has been removed from the owners of the Safe.

Maybe it's related to the fact the current webhooks don't cover this use case.

# Background
Given the following user flow:

1. Setup a 2/n Safe
2. Queue 2 transactions: The first one removes one of the owners, the second one can do anything else (i.e. transfer some funds)
3. Sign the second transaction fully, use the owner which will get removed in transaction 1
4. Sign and execute the owner removal transaction

It seems the transaction info doesn't get invalidated immediately. The `.../transactions/:transactionHash` endpoint returns the correct `confirmations` array, but the previous data containing the removed owner still present in the Client Gateway.

# Related issues
[Original issue detected by web team and QA.](https://github.com/safe-global/web-core/issues/1463)

# Endpoint
## URL
`GET /api/v1/safes/<address>/transactions/0x32358d479ebb37d579e5c2ceb51200d1388f38799d78bb076d7230afc797d774`

## Response
(**Transaction Service**)
```
...
"confirmationsRequired": 2,
    "confirmations": [
        {
            "owner": "0x3819b800c67Be64029C1393c8b2e0d0d627dADE2",
            "submissionDate": "2023-01-05T15:08:32.764037Z",
            "transactionHash": null,
            "signature": ...,
            "signatureType": "EOA"
        }
    ],
...
```

## Response
(**Client Gateway**)
```
...
"confirmationsRequired": 2,
    "confirmations": [
      {
        "signer": {
          "value": "0x3819b800c67Be64029C1393c8b2e0d0d627dADE2"
        },
        "signature": ...,
        "submittedAt": 1672931312764
      },
      {
        "signer": {
          "value": "0x6FEE06F2CDD7D82bCBe5fB787a930DE3D233ce67"
        },
        "signature": ...,
        "submittedAt": 1672931340128
      }
    ],
...
```

**Comment by Uxio0** [comment]
@hectorgomezv do you think this is still relevant?

**Comment by hectorgomezv** [comment]
Sorry about the delay, @Uxio0, I think I missed out the notification for your quote. 

I've been able to reproduce this issue: when the owner gets removed, their confirmation is also removed on the TXS side, but not in the CGW, as we invalidate the cache registries for the detail of the transaction being executed, and for the list of transactions. To solve this issue we would need to iterate over each element of that list and invalidate the detail of every transaction belonging to the Safe. So this is CGW-related, it's not a problem in the Transaction Service. I'm going to close the issue, sorry about the misinterpretation.

In my opinion, this is a corner case, and also purely UI-related (the Safe behaves as one could expect, i.e.: blocking the user from executing the transaction signed by the removed owner). The UI will show the _correct_ state as soon as the cache gets refreshed. So I'd leave this as it is, implementing a fix in the CGW would harm performance and would impact all the use cases involving transaction executions.

**Comment by Uxio0** [comment]
No worries @hectorgomezv , thanks for clarifying 🙏🏻
