### ISSUE TITLE
Periodically set trusted tokens using token list information

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1281]
# What is needed?
- Tokens `trusted` flag must be set using token lists
- A task must be created to update them (once a day looks like a good compromise)

# Background
Currently `trusted` tokens are marked manually. Scraping trusted token lists it's a good way to automatically update them. We will hardcode the following lists:

| Network  | List |
| ------------- | ------------- |
| mainnet  | [Coingecko](https://tokenlists.org/token-list?url=https://tokens.coingecko.com/uniswap/all.json)  |
| Polygon  | [Official List](https://api-polygon-tokens.polygon.technology/tokenlists/polygonTokens.tokenlist.json) |
| Optimism | [Official List](https://static.optimism.io/optimism.tokenlist.json) |
| Gnosis Chain | [Honeyswap ](https://tokens.honeyswap.org/) |
| BSC | [PancakeSwap](https://tokens.pancakeswap.finance/pancakeswap-extended.json) |
| Aurora | [Official List](https://aurora.dev/tokens.json) |

# Endpoint
Endpoints will not be updated as it's only an internal change.

**Comment by fmrsabino** [comment]
I was wondering about the removal of a token which seems to be more difficult to tackle efficiently.

If we have a list at day 0:

```json
{
  "tokenA": "<address>",
  "tokenB": "<address>" 
}
```

and then at day 1:
```json
{
  "tokenB": "<address>" 
}
```

`tokenA` should be marked as non-trusted correct? This might involve going through every token OR storing and building a diff between different token list version (maybe just using the last one is enough).

**Comment by Uxio0** [comment]
That's a nice catch, I didn't think of it. One solution would be to mark every token as `not trusted` and set them all again, but what happens to the ones we manually marked as `trusted`? Other solution would be what you say, remembering the last version of the list, but that still could break manually marked tokens.

**Comment by fmrsabino** [comment]
> That's a nice catch, I didn't think of it. One solution would be to mark every token as `not trusted` and set them all again, but what happens to the ones we manually marked as `trusted`? Other solution would be what you say, remembering the last version of the list, but that still could break manually marked tokens.

For the ones that we "manually" mark I'd suggest creating our own list and parse it in the same way as the other ones what do you think?

I would say that we would need to consider this as part of an atomic operation like:

1. Mark everything as `not trusted` (not sure if this can be done efficiently)
2. Mark every token in the list as `trusted`

If `1` or `2` fail for some reason I think we should revert.

------

Regarding the diff, I think it can be considered as a followup improvement if marking every token as not-trusted is considered to be an heavy operation. I would ignore the diff for the initial version honestly.

**Comment by Uxio0** [comment]
> For the ones that we "manually" mark I'd suggest creating our own list and parse it in the same way as the other ones what do you think?

I think that's way more job (creating the list, updating and storing them) but it sounds like the only good solution. We can go first with implementation not counting on manually `trusted` tokens and implement the custom lists if we see the need.

Agree on the atomic operation and ignoring the diff.

**Comment by Uxio0** [comment]
@fmrsabino I went with the proposed solution in the implementation https://github.com/safe-global/safe-transaction-service/pull/1289
