### ISSUE TITLE
How to add new blockchain ?

### ISSUE THREAD

**Issue by gzliudan** [safe-global/safe-transaction-service#1300]
# What is needed?
Support xinfin(mainnet) and apothem(testnet) blockchain in safe-transaction-service.

# Background
The xinfin and apothem blockchains are added in safe-deployments v1.18.0 already.

# Question
Is there a guide about how to add new blockchains into safe-transaction-service ?

**Comment by Uxio0** [comment]
Hi @gzliudan, you can add the network information to https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/management/commands/setup_service.py , but it will not be supported officially by us, so you would need to run the services yourself, you can take a look at https://github.com/safe-global/safe-infrastructure

**Comment by gzliudan** [comment]
Thanks
