### ISSUE TITLE
Review our current log for indexing tasks

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1319]
# What is needed?
Our current logs for ERC20 indexing looks like:
```
- 2023-02-09 13:24:11,773 Start indexing of erc20/721 events 
- 2023-02-09 13:24:15,198 Erc20EventsIndexer: Processing <number of addresses> almost updated addresses
- 2023-02-09 13:24:15,642 Erc20EventsIndexer: Found <number of events> events from block-number=<block-number> to block-number=<block-number> for <number of addresses> addresses
- 2023-02-09 13:24:15,777 Indexing of erc20/721 events task processed <number of events> events 
- 2023-02-09 13:24:15,778 Task safe_transaction_service.history.tasks.index_erc20_events_task[celery-task-id] succeeded in <number of seconds> : <number of events>
```
I would like to reduce the number of lines and the repeated information like `number of events`.
Also I would like to add the number of blocks processed in this line `Task safe_transaction_service.history.tasks.index_erc20_events_task[celery-task-id] succeeded in <number of seconds> : <number of events> ` like following:
`Task safe_transaction_service.history.tasks.index_erc20_events_task[celery-task-id] succeeded in <number of seconds> : <number of events> , <number of blocks processed>`

**Comment by Uxio0** [comment]
Sounds good, let's prepare a PR and discuss over that for the concrete lines that should be logged
