### ISSUE TITLE
Indexing issue in case of batching module txs in the nested safe

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-transaction-service#1372]
**Describe the bug**
Indexing issue in case of batching module txs in the nested safe

**To Reproduce**
1. 3 module txs created in the "parent safe" were confirmed and executed as a batched tx in the "owner safe"  
 https://safe-transaction-gnosis-chain.safe.global/api/v1/safes/0x00B0CbB97F5509492E33caCAcf0F4f88235FcFbA/module-transactions/
As a result, they are identical, only the "to" field is different for all 3 txs ( "transactionHash": "0x8f9acc2f904d673cbeeea27eb47da87dc9718f5e963ad0ff7952be630fa37536")

2. the txs are indexed as one tx with an incorrect value ( 30xdai instead of 90 xdai) - https://safe-transaction-gnosis-chain.safe.global/api/v1/safes/0x00B0CbB97F5509492E33caCAcf0F4f88235FcFbA/all-transactions/?executed=false&queued=true&trusted=true
<img width="785" alt="image" src="https://user-images.githubusercontent.com/338622/225318492-4e3291f0-4093-427b-b9d1-ccb5004d4f41.png">

**Expected behavior**
The txs should be returned as 3 module txs with a valid value

**Environment (please complete the following information):**
 - production
 - gnosis chain
 - Browser chrome/MM on mobile
 - Version "name": "Safe Transaction Service",
                  "version": "4.16.0",

**Comment by Uxio0** [comment]
It's indeed an issue on our side:

It happens here: https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/services/transaction_service.py#L313

We need to refactor the service to support more than one `ModuleTransaction` per `EthereumTx`
