### ISSUE TITLE
Block process keeps in 1 block until restart

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1381]
**Describe the bug**
When an error happens requesting something to the node the `block_process` is updated to 1 and the issue seems that sometimes is not coming back to higher values until restart the indexer. 
`block_process` is the number of blocks that the transaction-service request to RPC during indexing process, can be more or less blocks depending on the response of RPC. 
`block_process` is calculated automatically in [auto_adjust_block_limit](https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/indexers/ethereum_indexer.py#L307). 
This calculate a delta time when interact with RPC node and take some decisions like increase the `block_process`, reduce or  keep the `block_process`.
`block_process` back to 1 when there's a timeout or an error in the RPC provider response. https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/indexers/ethereum_indexer.py#L396 

**One potential explanation**
When block_process limit backs to 1 because an error, the delta time keeps in the place where `auto_adjust_block_limit` doesn't change the value. This could happen because the RPC node is taking the same time querying 1 block than 50 blocks for example.  

**Expected behavior**
`block_process` variable should be able to reach 1 when things are not going well with the node and come back again to higher values when everything is ok. 

**Possible solutions**
- try to back to default value after some time
- make more specific exceptions to handle when really is necessary set 1 block process limit

**Comment by Uxio0** [comment]
Fixed by #1422
