### ISSUE TITLE
Add Syscoin Networks (Tanenbaum, Syscoin Mainnet, ROLLUX) 

### ISSUE THREAD

**Issue by GundamDweeb** [safe-global/safe-transaction-service#1389]
# What is needed?
Adding in support (only price handling) to the transaction service.

Relies on : 

https://github.com/safe-global/safe-singleton-factory/issues/123
https://github.com/safe-global/safe-singleton-factory/issues/124
https://github.com/safe-global/safe-singleton-factory/issues/125

&
https://github.com/safe-global/safe-eth-py/issues/487

# Background
Syscoin requires intergration with the Safe. 

# Related issues
https://github.com/safe-global/safe-singleton-factory/issues/123
https://github.com/safe-global/safe-singleton-factory/issues/124
https://github.com/safe-global/safe-singleton-factory/issues/125
https://github.com/safe-global/safe-eth-py/issues/487

ATT: @develcuy

**Comment by Uxio0** [comment]
If you want this implemented please send a PR to https://github.com/safe-global/safe-eth-py
