### ISSUE TITLE
How to apply for API key?

### ISSUE THREAD

**Issue by GopherJ** [safe-global/safe-transaction-service#1390]
Hi,

I used generate complex contract upgrade function data and post it via safe transaction service here: https://github.com/para-space/paraspace-core/blob/4bf4a78907976b82d3e68fd034c3abb06df3cfd8/helpers/contracts-helpers.ts#L917-L981

and I also have a hardhat task which fetches & decode pending safe transactions https://github.com/para-space/paraspace-core/blob/4bf4a78907976b82d3e68fd034c3abb06df3cfd8/tasks/dev/safe.ts#L14-L81

It used to work fine for months and I use directly https://safe-transaction-mainnet.safe.global/ without problems, but today I just found that I start to receive `Forbidden` status code. Am I blocked and can I get the API key?

**Comment by GopherJ** [comment]
could someone DM me an API key on  twitter.com/0xJ_C, great thanks!

**Comment by Uxio0** [comment]
There's no API Key, but we have a rate limit in place and that could be the issue
