### ISSUE TITLE
Add support for Safe Contracts v1.4.1

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1433]
# What is needed?
Support Safe Contracts v1.4.1 when the Safe-contracts release is ready

# Background
Some events change their signature and `v1.4.1` ABI needs to be loaded into the `SafeEventsIndexer`

# Related issues
- Issue changing the events: https://github.com/safe-global/safe-contracts/pull/542
- Requires to merge the decoder update to allow multiple ABIs per topic: https://github.com/safe-global/safe-transaction-service/pull/1434
- https://github.com/safe-global/safe-deployments/pull/229
- https://github.com/safe-global/safe-deployments/pull/239
- https://github.com/safe-global/safe-eth-py/issues/583

# Tasks
- [ ] Add tests for v1.4.1

**Comment by mattstam** [comment]
@moisses89 Any progress on this?

**Comment by moisses89** [comment]
> @moisses89 Any progress on this?

We are currently working on it, first adding the contracts to [safe-eth-py](https://github.com/safe-global/safe-eth-py/issues/583) then we will continue with this issue.
