### ISSUE TITLE
Migration script for internal Safe Apps links

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-transaction-service#1469]
# What is needed?
A migration script to change apps transactions origin from apps.gnosis-safe.io domain to apps-portal.safe.global

# Background
We are migrating our internal apps from the old apps.gnosis-safe.io domain to apps-portal.safe.global. Overall it should be a simple transition but for the best UX a migration on transaction `origin` details updating the internal apps to the new domain will be a better user experience, as removing the old link will result on the interface not being able to resolve the image and app name to display on the transaction list, showing instead a bare "Contract interaction"

# Related issues
https://github.com/safe-global/safe-react-apps/issues/697

# Endpoint
At least will affect the following endpoints:

## URL
`GET /api/v1/safes/<address>/all-transactions/`
`GET /api/v1/safes/<address>/multisig-transactions/`
`GET /api//v1/multisig-transactions/{safe_tx_hash}/`

**Comment by Uxio0** [comment]
Updating `apps.gnosis-safe.io` -> `apps-portal.safe.global` will take us from `19 chars` to `23 chars`. What should be the behaviour if that change exceeds the field size? I would propose to increase a little the database field in the same migration so we don't run into that issue

**Comment by dasanra** [comment]
@Uxio0 sorry that we forgot to explicitly answer here. Will it become a problem with other apps that will now have also 4 more chars for the url?
