### ISSUE TITLE
Add Multisend contracts to configuration with endpoint

### ISSUE THREAD

**Issue by DefiDebauchery** [safe-global/safe-transaction-service#1470]
# What is needed?
Safe keeps a list of its multisend contract addresses in `safe-deployments`, but it's a bit unwieldy to parse. Far better would be to have this stored within the TXS, as other per-chain contracts are stored here.

# Endpoint
`/v1/about/contracts/multi-send`

## Response
```
{
  multiSend: "0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761",
  multisendCallOnly: "0x40A2aCCbd92BCA938b02010E17A5b8929b49130D",
}
```

**Comment by Uxio0** [comment]
Sounds like a good idea, thanks for the suggestion

**Comment by Uxio0** [comment]
Superseeded by #1996
