### ISSUE TITLE
404 for Newly Deployed Safes on Base Testnet

### ISSUE THREAD

**Issue by mozrt2** [safe-global/safe-transaction-service#1491]
**Describe the bug**
When deploying a Safe on Base Testnet, both via the web ui and the protocol SDK, the Safe gets deployed correctly but the Safe Client and the Safe Transaction Service return a 404. This means that the Safe can also not be loaded inside the Safe Web UI. 
![image](https://github.com/safe-global/safe-transaction-service/assets/79607357/3d814561-db2b-4c3e-8cb4-9c8a447e0332)

This seems to only be an issue for newly created Safes.

**To Reproduce**
1. Create a new Safe on Base Testnet at https://app.safe.global/new-safe/create
2. The Safe gets deployed successfully but is stuck at the indexing step as `https://safe-client.safe.global/v1/chains/84531/safes/[ADDRESS]` returns a 404
![image](https://github.com/safe-global/safe-transaction-service/assets/79607357/ca748749-0dcf-4892-8bbc-51e0d0b19c99)

Same issue when trying to access the Safe at `https://safe-transaction-base-testnet.safe.global/api/v1/contracts/[ADDRESS]`

**Expected behavior**
The Safe Client and Safe Transaction Service respond with 200 and the data of the newly created Safe.

**Environment (please complete the following information):**
 - Base Testnet
 - Both via Web UI & Protocol SDK

**Comment by moisses89** [comment]
@mozrt2 thanks to share with us this, looks that was fixed, could you double check?

**Comment by mozrt2** [comment]
@moisses89 yes, I just checked and this is fixed, thank you!
