### ISSUE TITLE
Too many redis client connections by safe-transaction

### ISSUE THREAD

**Issue by ausias-armesto** [safe-global/safe-transaction-service#1501]
**Description**
A running instance of safe-transaction configured with a Gnosis chain and without users still using the service is consuming more than 400 redis connections. Even after the initial sync period with the Gnosis Chain

**To Reproduce**
1. setup safe-transaction server with Gnosis
2. Connect to the Redis server and count the opened connections

```
REDISCLI_AUTH=$REDIS_PASSWORD redis-cli CLIENT LIST | sed -n 's|.*addr=\(.*\)\:.*|\1|p' | sort | uniq -c

    434 10.2.89.158
      1 127.0.0.1
```

**Expected behavior**
I would expect to have a lower number of connections and be sure

**Environment (please complete the following information):**
 - Staging
 - Gnosis
 - Using a local installation of Safe Global (v4.18.6)

**Additional context**
There are other metrics which are quite strange regarding the usage of Redis. Here I show some metrics from Grafana

<img width="1480" alt="Screenshot 2023-06-09 at 08 52 08" src="https://github.com/safe-global/safe-transaction-service/assets/29434949/48d8d2f8-4749-4c32-beea-2361f7a82e09">
<img width="747" alt="Screenshot 2023-06-09 at 08 52 49" src="https://github.com/safe-global/safe-transaction-service/assets/29434949/7eb48195-419e-4aae-b648-5ee8b2c7ab78">

**Comment by Uxio0** [comment]
Hi @ausias-armesto ,

We use a connection pool and don't limit the number of connections. Do you see any Redis issue, massive usage of CPU or memory?

**Comment by ausias-armesto** [comment]
> Hi @ausias-armesto ,
> 
> We use a connection pool and don't limit the number of connections. Do you see any Redis issue, massive usage of CPU or memory?

Could you give me some examples on where do you use the connection pool and how. I expected that the application itself would manage those issues and not at the infrastructure level. I don't see any exceptional CPU or memory consumption, but we have a prometheus alert firing constantly indicating a posible bad usage of redis connections

**Comment by Uxio0** [comment]
https://github.com/safe-global/safe-transaction-service/blob/5935251c3b568b3108425f2c4bef8decd448a3cc/safe_transaction_service/utils/redis.py#L7

It's `cached`, so we always reuse the same redis client

**Comment by ausias-armesto** [comment]
> https://github.com/safe-global/safe-transaction-service/blob/5935251c3b568b3108425f2c4bef8decd448a3cc/safe_transaction_service/utils/redis.py#L8-L10
> 
> It's `cached`, so we always reuse the same redis client

I already looked at the `cached` annotation before opening the bug, and wondered why there were still so many redis client connections if they are cached, and thought that perhaps it's not working (caching) as expected.

**Comment by Uxio0** [comment]
I rechecked and I don't see any issue here. [ConnectionPool must be used when calling from_url](https://redis-py.readthedocs.io/en/stable/connections.html#redis.Redis.from_url). But remember web service can run with some threads (1 redis pool for thread) and also every worker (indexer, contracts and notification) holds a redis connection

**Comment by ausias-armesto** [comment]
I @Uxio0 , I don't know how to handle this, as the metrics gathered from the monitoring are also quite significant that the cache might not be working.

Perhaps, it would be nice to know which is the expected number of redis connections to be opened by the service in a standard scenario.

Would you be able to run this command in your development/staging/production environment ?
````
REDISCLI_AUTH=$REDIS_PASSWORD redis-cli CLIENT LIST | sed -n 's|.*addr=\(.*\)\:.*|\1|p' | sort | uniq -c
````

**Comment by ausias-armesto** [comment]
Thanks @Uxio0 , It's nice to know that we have similar numbers on the metric. Then, I would say that it's time to consider if that value is considered correct. I applied this [prometheus rule](https://samber.github.io/awesome-prometheus-alerts/rules#rule-redis-1-10) where it recommends not to have more than 90.
Should this be changed at the application level?

**Comment by Uxio0** [comment]
Hi @ausias-armesto , I don't think is relevant that someone decided that 90 connections to redis are too much. Taking a look in the offical docs I don't see any kind of problem or recommendation: https://redis.io/docs/reference/clients/ . Also in our production environments we don't see any issues

**Comment by Uxio0** [comment]
@ausias-armesto thanks for the detailed reports on this issue, but we still didn't find any issue in our production deployments so we decided not to do anything about this
