### ISSUE TITLE
Price calculation tasks delayed

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1504]
**Describe the bug**
Price calculation tasks occasionally experience delays due to the execution of the `reindex_contracts_without_metadata_task`, which occurs on a weekly basis. This particular task often involves reindexing a large number of contracts, causing a significant workload. 
Moreover, for each contract requiring reindexing, an additional task called `create_or_update_contract_with_metadata_task` is appended to retrieve contract information. In a recent instance, around 80,000 tasks were executed on Polygon.
The execution of these tasks is immediate, leaving little room for the price calculation tasks to run. Consequently, the price calculation process occasionally experiences delays of more than one day, resulting in token prices appearing as 0 when the cache of each price is expired.

**Proposed solution**
Modify the frequency of this task to every day or 2 days to reduce the number of contracts to be reindexed.

**Comment by Uxio0** [comment]
This might be fixed by https://github.com/safe-global/safe-transaction-service/pull/1520

I would analyze also if maybe we should have less Celery workers to be able to attend all the requests and not having a lot of tasks running at the same time that the service cannot handle

**Comment by Uxio0** [comment]
Currently concurrency is set to `1_000` tasks. Maybe that's too much concurrent gevent threads, and we could be more conservative and maybe get a speed up by reducing it

**Comment by Uxio0** [comment]
Price calculation was removed from the tx service in favour of the https://github.com/safe-global/safe-price-service/
