### ISSUE TITLE
How can I found all the safe addresses by the using my wallet address in polygon(mumbai) testnet

### ISSUE THREAD

**Issue by Aayush3Intervision** [safe-global/safe-transaction-service#1507]
# I want to know how can I found the safe address?
My wallet address is owner in some safe and I want to know how can I get all the safe addresses with mumbai testnet.
# Background
It will help other developers to build on different testnet.

**Comment by Uxio0** [comment]
Note that we don't run a service for mumbai, so you would need to find someone that does or run it yourself 🙂
