### ISSUE TITLE
Improve performance of get all transactions identifiers

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1519]
# What is needed?
The function `get_all_txs_identifiers` can for some safes consume a lot of resources of database, we should take a look into this and search ways to improve the performance of this query.
![image](https://github.com/safe-global/safe-transaction-service/assets/7888669/c343f6e1-e9ea-40d5-aa83-23e5707030a8)

# Background
Get all transactions identifiers get information for every type of transaction that involved the safe, this means that to get this goal the query is doing several joins and unions, and this type of query for some safes is consuming a lot of resources.

# Related issues
No issues related

# Proposed solutions
- Add a new table to add every transaction in the same place avoiding a lot of of joins and unions that do this query very heavy. 
- Denormalize the database, [adding more fields so UNION ALL can use indexes, as it seems in some cases it can](https://stackoverflow.com/a/75289601/724991)
- Add limits to this big safes, as for example only offer the last 100.000 transactions

**Comment by Uxio0** [comment]
https://github.com/safe-global/safe-transaction-service/pull/1611 is improving the query time

**Comment by Uxio0** [comment]
https://github.com/safe-global/safe-transaction-service/pull/1575 is caching the result and should reduce a lot the impact to the database
