### ISSUE TITLE
Safe Transactions API Gnosis-Chain endpoint now returns 404 on all requests despite working just a few days ago

### ISSUE THREAD

**Issue by robriks** [safe-global/safe-transaction-service#1557]
**Describe the bug**
API requests to Gnosis-Chain endpoint, ie `https://safe-transaction-gnosis-chain.safe.global/` now return 404 errors despite working just a few days ago. I had been using the `/v1/safes/{address}/` endpoint to grab the nonce for a Gnosis Safe contract and now it is broken.

**To Reproduce**
1. Do GET on 'https://safe-transaction-gnosis-chain.safe.global/v1/safes/{address}/'
  - Provide any valid Safe contract `{address}` such as in my case: `0x1C207262275b203eAB914330abD947cB787aD3A1` ie:
  `https://safe-transaction-gnosis-chain.safe.global/v1/safes/0x1C207262275b203eAB914330abD947cB787aD3A1` and only response is either 304 (permanently moved) or 404 (not found)

**Expected behavior**
A response in line with the API reference and documentation, which details a SafeInfoResponse object containing among other things the Safe nonce. This had been working just days ago.

**Environment (please complete the following information):**
-  Production
 - Gnosis-Chain
 - OS: n/a but ubuntu
 - Browser: Firefox
 - Version: 114.0.1

**Additional context**
This is for a project with a deadline and I am unable to continue work on it until the Gnosis-Chain API is fixed, unless there is a better way of obtaining the Safe contract nonce that I am unaware of. Would very much appreciate another option than using the API if the fix cannot be completed quickly.

**Comment by moisses89** [comment]
Hey @robriks the safe infor endpoint is working correctly, the address that you are providing to the endpoint is not a valid safe contract https://gnosisscan.io/address/0x1C207262275b203eAB914330abD947cB787aD3A1#code it is a custom contract.
