### ISSUE TITLE
Django admin fonts not found

### ISSUE THREAD

**Issue by ausias-armesto** [safe-global/safe-transaction-service#1564]
**Describe the bug**
In a running instance of the safe-transaction-service I've been reviewing logs while developers are accessing the admin site and have found that there are nginx errors trying to get the fonts from Django admin.

The log error is the following:
````
GET https://safe-transaction.stage.hoprtech.net/static/admin/fonts/Roboto-Bold-webfont.woff 404
````

After reviewing the Docker image, I see that the /staticfiles/admin is generated in the last [RUN command](https://github.com/safe-global/safe-transaction-service/blob/master/docker/web/Dockerfile#L31)

But surprisingly, the `fonts` folder is not generated and filled with *.woff files.

**To Reproduce**
1. Run a safe-transaction-service container
2. `docker exec -it safe-transaction-service /bin/bash`
3. From within the container: `ls -al /app/staticfiles/admin/`
4. Check that the `fonts` folder is not created.

**Expected behavior**
Don't see error logs of files not found

**Environment (please complete the following information):**
 - Staging
 - Gnosis
 - v4.18.6

**Comment by Uxio0** [comment]
This is not very relevant for us, but if you work in a PR we will merge
