### ISSUE TITLE
[GET] /api/v1/safes/:safeAddress - Nullable version field

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-transaction-service#1571]
**Describe the bug**
When retrieving a Safe info, `null` version field is returned, even though the OpenAPI definition for this service explicitly indicates `SafeInfoResponse.version` is not nullable.

**To Reproduce**
1. GET  [URL](https://safe-transaction-gnosis-chain.safe.global/api/v1/safes/0xa08826D91a104d31856F448190B346f077e3EABb/)
2. Returns:
```
{
  "address": "0xa08826D91a104d31856F448190B346f077e3EABb",
  "nonce": 0,
  "threshold": 1,
  "owners": [
    "0x3955bDB84795fD30522F15A123C68792D3aAAf80"
  ],
  "masterCopy": "0x0000000000000000000000000000000000000000",
  "modules": [
    "0x3955bDB84795fD30522F15A123C68792D3aAAf80"
  ],
  "fallbackHandler": "0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4",
  "guard": "0x0000000000000000000000000000000000000000",
  "version": null
}
```

**Expected behavior**
`version` field shouldn't contain null values.

**Comment by moisses89** [comment]
@hectorgomezv we are going to change the `openapi` doc to include `nullable` version. 
Version is going to be null if the `masterCopy` address is not one of the deterministic known addresses.

**Comment by moisses89** [comment]
As I can see version is currently nullable on openApi from this [commit](https://github.com/safe-global/safe-transaction-service/commit/66ad769a84bc42f536627bc92bffcc863cfd3250#diff-ffa3f7602acc3a07a0d3bb820224a2d4a1c49e4c0a40bf8d3f32e8d3111cbbb5R701)
Which version of openApi are you using? https://redocly.com/docs/api-reference-docs/specification-extensions/x-nullable/
![image](https://github.com/safe-global/safe-transaction-service/assets/7888669/4357db82-1538-4a3b-9c4b-921f642e3707)

**Comment by hectorgomezv** [comment]
Yes, there's a misalignment between the OpenAPI and the inner validation schema. We need to fix the validation schema. Thanks for noticing @moisses89

**Comment by hectorgomezv** [comment]
Closing this, as this behavior is expected. Further changes must be made in the Client Gateway to accept nullable version fields.
