### ISSUE TITLE
Replace links pointing to the Safe Dev Docs

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-transaction-service#1576]
In the README file of this project some links pointing to the Safe docs need to be updated:

- **In line 23**
Replace `https://docs.gnosis-safe.io/backend/service-architecture` with `https://docs.safe.global/safe-core-api/service-architecture`

- **In line 181**
Replace `https://docs.safe.global/learn/infrastructure/rpc-requirements` with `https://docs.safe.global/safe-core-api/rpc-requirements`

- **In line 190**
Replace `https://docs.safe.global/learn/safe-core/safe-core-api/available-services` with `https://docs.safe.global/safe-core-api/available-services`

I didn't create a Pull Request because I don't have permissions.

**Comment by Uxio0** [comment]
I was not aware of that, you have now permissions 😉
