### ISSUE TITLE
Ignore untrusted transactions in `get_unique_nonce`

### ISSUE THREAD

**Issue by DefiDebauchery** [safe-global/safe-transaction-service#1618]
**Describe the bug**
"Untrusted" transactions are considered when evaluating the next available nonce, causing applications (including the Safe UI) to skip over it for new Transaction Proposals, disrupting the ability for signers to further manage the Safe.

**To Reproduce**
I'm unsure how exactly to trigger the underlying issue, but it appears that creating a batched transaction that is later abandoned still creates a pending transaction in the Safe Transaction Service, but is marked "untrusted".

Either way, if you can make an untrusted transaction be the most recent transaction, you can see this behavior.

Untrusted Transactions do not show in the list of Pending transactions, so without knowing the nonce, normal users cannot act on the transaction. Similarly, `get_unique_nonce()` is not currently filtering these out, so `/v1/safes/{address}/multisig-transactions` will include it in its `countUniqueNonce` output.

https://github.com/safe-global/safe-transaction-service/blob/3644c08ac4b01b6a1c862567bc1d1c81b1a8c21f/safe_transaction_service/history/views.py#L595-L598

**Expected behavior**
Only trusted transactions should contribute to `countUniqueNonce`, so that the next available nonce can be properly evaluated

**Comment by Uxio0** [comment]
You are right @DefiDebauchery , this is really important and we will work on it as soon as posible

**Comment by Uxio0** [comment]
Hi @DefiDebauchery , I totally forgot about this, and trying to implement the fix I realised what was the meaning of this parameter.

`count_unique_nonce` only returns the number of different `nonces` that are on database, not the last `nonce`, but that could match. With a tx with `nonce=1` and other with `nonce=5`, `count_unique_nonce` will be `2`.

So I will improve the documentation and also add the parameter you proposed
