### ISSUE TITLE
Adding CASH token to Safe

### ISSUE THREAD

**Issue by stabl-labs** [safe-global/safe-transaction-service#1619]
# What is needed?
We would like for the CASH token to be added to Safe so protocols using CASH will see accurate portfolio values under the asset tab on Safe.

The Token address is:
$CASH Token Address: 0x5d066d022ede10efa2717ed3d79f22f949f8c175

CASH Coingecko link: https://www.coingecko.com/en/coins/stabl-fi-cash
Website link: https://stabl.fi/
Docs: https://docs.stabl.fi/protocol-overview/introducing-stabl.fi

# Background
More information about the feature needed
Stabl.fi is a next-generation, yield bearing stable indexcoin protocol. Users mint $CASH by depositing stables into the Stabl protocol. The amount of $CASH in your wallet will continually grow, due to the yield strategies the protocol deposited stables are put in as well as external yielding sources.
Fully collateralized: For every $CASH in circulation, there is stablecoin collateral backing it. 
$CASH supports collateral deposits of USDC, USDT, and DAI - the most trusted stablecoins in DeFi
$CASH is always redeemable for the same value as your deposit (minus fees)
Collaterals are put in the safest yielding strategies available. Collateral security is priority #1.

# Related issues
Paste here the related links for the issues on the clients/safe project if applicable. Please provide at least one of the following:
- Links to epics in your repository
- Images taken from mocks
- Gitbook or any form of written documentation links, etc. Any of these alternatives will help us contextualise your request.

# Endpoint
If applicable, description on the endpoint and the result you expect:

## URL
`GET /api/v1/safes/<address>/creation/`

https://stabl.fi/

## Response
```
{
  created: "<iso 8601 datetime>",
  transactionHash: "<keccak-hash>",
  creator: "<checksummed-address>"
}
```

**Comment by moisses89** [comment]
@stabl-labs we are not adding manually tokens to the transaction service, each token is stored on database when the token is received first time in any safe.
