### ISSUE TITLE
Bug in Data Field of details an Multisig-transactions into tx-indexer

### ISSUE THREAD

**Issue by alfredolopez80** [safe-global/safe-transaction-service#1626]
**Describe the bug**
When the tx-indexer indexes an internal tx, it does not capture the correct input data, but rather the call to the tx, so even when the tx-indexer has the ABI's contract indexed, it is not capable of decoding said tx, the fact It can be verified if you compare the "data" field with the "input data" from the explorer (in this case from polygonscan.com).

**To Reproduce**
1. Do POST on 'https://safe-transaction-polygon.safe.global/api/v1/safes/0x9c13ec42FF06300aEa10701A58cdE6eddaaD56c0/multisig-transactions/'
`"count": 30,
  "next": null,
  "previous": null,
  "results": [
    {
      "safe": "0x9c13ec42FF06300aEa10701A58cdE6eddaaD56c0",
      "to": "0x3aD736904E9e65189c3000c7DD2c8AC8bB7cD4e3",
      "value": "0",`
      **"data": "0x160e8be300000000000000000000000000000000000000000000000003782dace9d90000",**
      `"operation": 0,
      "gasToken": "0x0000000000000000000000000000000000000000",
      "safeTxGas": 0,
      "baseGas": 0,
      "gasPrice": "0",
      "refundReceiver": "0x0000000000000000000000000000000000000000",
      "nonce": 29,
      "executionDate": "2023-08-11T22:33:38Z",
      "submissionDate": "2023-08-11T22:31:24.334353Z",
      "modified": "2023-08-11T22:35:15.316605Z",
      "blockNumber": 46192592,
      "transactionHash": "0xd674d9ae4c271a301f7096b94b1581ad436a982350f4e12ae19cc1f018f1845f",
      "safeTxHash": "0x7862001cf0163749d1a6d83558c730143545c8d38a96753a96cf553797ec9f36",
      "executor": "0xf0658Be12010dDD04c6497fd17a721C0935fc3ca",
      "isExecuted": true,
      "isSuccessful": true,
      "ethGasPrice": "113736950738",
      "maxFeePerGas": null,
      "maxPriorityFeePerGas": null,
      "gasUsed": 215966,
      "fee": "24563314303082908",
      "origin": "{\"url\": \"https://app.superfluid.finance\", \"name\": \"Superfluid Dashboard\"}",
      "dataDecoded": {
        "method": "downgradeToETH",
        "parameters": [
          {
            "name": "wad",
            "type": "uint256",
            "value": "250000000000000000"
          }
        ]
      },
      "confirmationsRequired": 2,
      "confirmations": [
        {
          "owner": "0x09A9D8aA5D8168701bC23b5BC5b13205f456De53",
          "submissionDate": "2023-08-11T22:31:24.407379Z",
          "transactionHash": null,
          "signature": "0x604dacd33506d92fbd40dd215e909acd6c3ad3505e5241d8b96bb1ab7aa46f7d7256dabcb37801c962426b0270ea5d5ff60e931216eabd68319cfa7f27a94baa1c",
          "signatureType": "EOA"
        },
        {
          "owner": "0xf0658Be12010dDD04c6497fd17a721C0935fc3ca",
          "submissionDate": "2023-08-11T22:32:03.291298Z",
          "transactionHash": null,
          "signature": "0xc4d4dde9d5c05433f0ed1315fcb611c1449b10074f14f17cf8754fda6cd5b06a61a09d41c164175457b2e83337ab0a6a578f5d6a4dd6e972a91b405f689f51a51c",
          "signatureType": "EOA"
        }
      ],
      "trusted": true,
      "signatures": "0x604dacd33506d92fbd40dd215e909acd6c3ad3505e5241d8b96bb1ab7aa46f7d7256dabcb37801c962426b0270ea5d5ff60e931216eabd68319cfa7f27a94baa1cc4d4dde9d5c05433f0ed1315fcb611c1449b10074f14f17cf8754fda6cd5b06a61a09d41c164175457b2e83337ab0a6a578f5d6a4dd6e972a91b405f689f51a51c"
    },`
2. Then GET on 'https://polygonscan.com/tx/0xd674d9ae4c271a301f7096b94b1581ad436a982350f4e12ae19cc1f018f1845f'
we get this:
<img width="1229" alt="Captura de pantalla 2023-08-14 a la(s) 13 03 45" src="https://github.com/safe-global/safe-transaction-service/assets/20690133/83774b43-5d07-4015-ae35-b3a0b944a71f">

3. Links to issues in other repos (if possible)
  N/A

**Expected behavior**
the field `data` must be the same in `input data` in the explorer, inclusive, if we take de `input data` for this tx and use the endpoint '/v1/data-decoded/` we can getting the details about this tx, but in th tx-indexer we can't because is not indexed the data properly.

**Environment (please complete the following information):**
 - Production
 - Which chain: Polygon
 - OS: Docker Imagen tx-indexer
 - Browser: Chrome Google
 - Version: 4.23.0

**Additional context**

**Comment by moisses89** [comment]
It is not an issue, it is correctly indexed and stored in EthereumTx model in `data` field because is the data of ethereum transaction. 
`MultisigTransaction` data is the data passed to `execTransaction` when was called. Take a look to the following EthereumTx data decoded, you can see that data value is exactly the same value than the response data you shared. 
```
{
  "method": "execTransaction",
  "parameters": [
    {
      "name": "to",
      "type": "address",
      "value": "0x3aD736904E9e65189c3000c7DD2c8AC8bB7cD4e3"
    },
    {
      "name": "value",
      "type": "uint256",
      "value": "0"
    },
    {
      "name": "data",
      "type": "bytes",
      "value": "0x160e8be300000000000000000000000000000000000000000000000003782dace9d90000",
      "valueDecoded": {
        "method": "downgradeToETH",
        "parameters": [
          {
            "name": "wad",
            "type": "uint256",
            "value": "250000000000000000"
          }
        ]
      }
    },
    {
      "name": "operation",
      "type": "uint8",
      "value": "0"
    },
    {
      "name": "safeTxGas",
      "type": "uint256",
      "value": "0"
    },
    {
      "name": "baseGas",
      "type": "uint256",
      "value": "0"
    },
    {
      "name": "gasPrice",
      "type": "uint256",
      "value": "0"
    },
    {
      "name": "gasToken",
      "type": "address",
      "value": "0x0000000000000000000000000000000000000000"
    },
    {
      "name": "refundReceiver",
      "type": "address",
      "value": "0x0000000000000000000000000000000000000000"
    },
    {
      "name": "signatures",
      "type": "bytes",
      "value": "0x604dacd33506d92fbd40dd215e909acd6c3ad3505e5241d8b96bb1ab7aa46f7d7256dabcb37801c962426b0270ea5d5ff60e931216eabd68319cfa7f27a94baa1cc4d4dde9d5c05433f0ed1315fcb611c1449b10074f14f17cf8754fda6cd5b06a61a09d41c164175457b2e83337ab0a6a578f5d6a4dd6e972a91b405f689f51a51c"
    }
  ]
} 
```
Also data-decoder is working fine from my side with the data of `multisigTransaction` json, maybe you missing to include the to field: 
```
curl -X 'POST' \
  'https://safe-transaction-polygon.safe.global/api/v1/data-decoder/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFToken: LeimeNV5NNQeQkqcow35kTv1O6jr6X2XSWE9o5Q70hQ1u2ANL5C5CysGlLtPJqCA' \
  -d '{
  "data": "0x160e8be300000000000000000000000000000000000000000000000003782dace9d90000",
  "to": "0x3aD736904E9e65189c3000c7DD2c8AC8bB7cD4e3"
}'
```
