### ISSUE TITLE
Ownership change events after setup within same tx not being picked up

### ISSUE THREAD

**Issue by tolbrino** [safe-global/safe-transaction-service#1635]
We are experiencing issues deploying Safe instances through our factory contract. Here is an example:

https://gnosisscan.io/tx/0x66425f06902a0ffc50d041599e60830d94d666c433e603095d03fca5897673b7#eventlog

The problem is that the tx service endpoint `/owners/MY_ACCOUNT/safes` won't return the newly created Safe. We tracked down the issue further and believe the problem lies in the switch of ownership during the deployment. This does not seem to be picked up by the indexer and it continues to "believe" the Safe is owned by our factory contract.

**Comment by QYuQianchen** [comment]
To give a little bit more context: When a safe proxy is created with `createProxyWithNonce`, the sole owner is set to the `msg.sender` which is a factory contract (StakeFactory). Within the same transaction, after a few other internal transactions, the owner of the safe proxy is swapped to a different EOA address. 
Given the owner of the safe proxy is a contract, the signature gneration follows EIP-1271, i.e. `approveHash` then `execTransaction`. Payload of the `swapOwner` safe transaction is thus encoded in `execTransaction`.
What we've observed is that, for the said proxy creation call, in the safe-transaction-service, only `setup` and `approveHash` internal calls got indexed.

**Comment by moisses89** [comment]
Maybe is related with the contract version, we are currently working adding support for 1.4.1 version https://github.com/safe-global/safe-transaction-service/issues/1433

**Comment by Uxio0** [comment]
As @moisses89 states, it would be important also to know what versions are you using of the contracts, as service should not have any problem detecting owner swap

**Comment by Uxio0** [comment]
Could you provide more feedback about this issue?

**Comment by QYuQianchen** [comment]
Hi there. Sorry that the thread got lost. We use contracts of v1.4.1

**Comment by JagoFigueroa** [comment]
Sorry for the delay guys. I see that the issue is resolved now so I will go ahead and close the ticket. Please let us know if you are still experiencing any issues 🙏
