### ISSUE TITLE
Command to update safe logos

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1636]
# What is needed?
We would like to include an easy way to update the logos of safe contract in the  Contracts model. 
An approach could be take the addresses of safe contract by version from every chain from https://github.com/safe-global/safe-deployments and update the logo addresses with the new logo. 

# Endpoints related
https://safe-transaction-mainnet.safe.global/api/v1/contracts/0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552/

**Comment by tschubotz** [comment]
@moisses89 when touching all Safe related known addresses/contracts, please also remove the word "gnosis" everywhere :) 

<img width="1122" alt="image" src="https://github.com/safe-global/safe-transaction-service/assets/1380529/98d280f9-1ee2-40e0-9284-5dcd802911fb">

**Comment by moisses89** [comment]
@Uxio0 I'm considering to expand the purpose of this issue to also create the missing contracts that are necessary by chain as multisend, what do you think?

**Comment by Uxio0** [comment]
> @Uxio0 I'm considering to expand the purpose of this issue to also create the missing contracts that are necessary by chain as multisend, what do you think?

Yes please, if they are available on the network we should create them if not (and also add their names)
