### ISSUE TITLE
SuperfluidGovernanceII ABI

### ISSUE THREAD

**Issue by d10r** [safe-global/safe-transaction-service#1653]
I come here because of https://help.safe.global/en/articles/40823-submit-an-abi

The contract base:0x55F7758dd99d5e185f4CC08d4Ad95B71f598264D is verified on basescan: https://basescan.org/address/0x55F7758dd99d5e185f4CC08d4Ad95B71f598264D#code
Yet pending Safe transactions to it show only hex data: https://app.safe.global/transactions/queue?safe=base:0xD8A05F504b5Ce16183D3e1e16FD6A365a8db53da

Is this because it's a proxy contract?

The relevant ABI can be found in the implementation contract: https://basescan.org/address/0xcfe6382b33f2adafbe46e6a26a88e0182ae32b0c#code

**Comment by Uxio0** [comment]
Yes, we don't support proxy contracts, but you should clarify that on the docs
