### ISSUE TITLE
Align `singleton` word use in our codebase

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-transaction-service#1665]
# What is needed?
Deprecate `master-copies` endpoint or add a new alias using `singletons`

# Background
Currently there is a missalignment between docs and codebase related to the term `master copy` and `singleton`. This creates confusion between developers as both terms refer to the same thing. As `singleton` is the way to go we should align all places where this reference is used. Not necessary to remove the `master-copies` endpoint directly but it should be possible to make this call also using `singletons`

# Endpoint
If applicable, description on the endpoint and the result you expect:
Have a `/singletons` endpoint that returns exactly the same as the current `master-copies`

## URL
`GET /api/v1/about/singletons/`

**Comment by Uxio0** [comment]
@fmrsabino @hectorgomezv you should be aware of this 😉
