### ISSUE TITLE
Support L2 Safes upgraded from non L2 Safes

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1703]
# What is needed?
Support L2 Safes upgraded from non L2 Safes

# Background
- When a non L2 Safe is replayed in a L2 network, indexer cannot pick it as `setup` event and initial state of the Safe is missed.
- We should find a way to support that kind of Safes in the UI.

# Related issues
- Implementing contract for version migration: https://github.com/safe-global/safe-contracts/pull/685
- Implementing command on safe-cli: https://github.com/safe-global/safe-cli/issues/285

# Example
- https://app.safe.global/home?chain=eth&safe=matic:0xBEFA89D90c112A416139F42046Cc2d4A8a308815

**Comment by JagoFigueroa** [comment]
Looks good to me, I was able to transact on a upgraded safe without any issues. [Here](https://app.safe.global/transactions/history?safe=matic:0x18D339380c46F431ddbD32b6f4749f6Aca24Be80) are a few transactions 😄

**Comment by Uxio0** [comment]
Working out of the box when using the provided contract on: https://github.com/safe-global/safe-smart-account/pull/685
