### ISSUE TITLE
Feature to allow decoding of call data for contracts that are proxies/diamonds

### ISSUE THREAD

**Issue by startswithaj** [safe-global/safe-transaction-service#1709]
# What is needed?
For Users that use proxy contracts or diamonds [ERC-2535](https://eips.ethereum.org/EIPS/eip-2535) the SAFE UI does not decode the transaction data. This is a known issue. Users are also not able to upload the abi for these contracts in anyway.

Feature:

1. In the address book allow users to configure an ABI for the address.
2. In the transaction panel (pictured below) add a button [Decode Data With Custom ABI].

This has been a problem for years for many users. Currently we must use a tool like https://lab.miguelmota.com/ethereum-input-data-decoder/example/ to verify call data or other custom tooling

Alternative:

Add a button that uses the https://www.4byte.directory/ or https://openchain.xyz/signatures api to check if there is a result for the function signature and if found use it to decode the call data.

# Background

<img width="1666" alt="Screenshot 2023-10-17 at 2 37 59 pm" src="https://github.com/safe-global/safe-transaction-service/assets/3658522/91503cdd-54f2-40a5-a436-bf9d0af460b1">

## URL
https://app.safe.global/transactions/

**Comment by Uxio0** [comment]
You are proposing web related fixes, so this issue belongs to https://github.com/safe-global/safe-wallet-web
