### ISSUE TITLE
Admin search is really slow for some models

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1710]
# What is needed?
Optimize search for admin pages like `InternalTxDecoded`, where any search always times out

# Background
Admin search is really slow for some models

**Comment by JagoFigueroa** [comment]
Hola team, sorry for the delay on testing this. 

I have been playing on Goerli and searches have been super smooth for me ✅

**Comment by Uxio0** [comment]
You were tagged a few hours ago, no delay at all!
