### ISSUE TITLE
Allow deleting queued transaction only signed by me

### ISSUE THREAD

**Issue by AlissonRS** [safe-global/safe-transaction-service#1737]
Hello!

In a multisig with multiple EOAs, let's say I propose a transaction, thus signing it myself.

If I'm the only one who signed it, what is the rationale behind not allowing me to remove/delete/unqueue that transaction myself (since no one else signed it yet)? I think there might be a reason for that, but I'm just failing to see it.

Thanks for such a great project!!!

**Comment by Uxio0** [comment]
Thanks for the suggestion, this feature has been in our roadmap for a long time and we will deal with it on https://github.com/safe-global/safe-transaction-service/issues/1757
