### ISSUE TITLE
Delete proposed not executed transactions

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1757]
# What is needed?
Allow proposed transactions to be deleted by the proposer:
- A signature from the proposer will be required.
- Add a event for transaction deletion so they can be refreshed from client gateway caches (different issue, #1805)

A EIP712 will be signed, and epoch will be included to prevent replay attacks

# EIP712
```python
{
    "types": {
        "EIP712Domain": [
            {"name": "name", "type": "string"},
            {"name": "version", "type": "string"},
            {"name": "chainId", "type": "uint256"},
            {"name": "verifyingContract", "type": "address"},
        ],
        "DeleteRequest": [
            {"name": "safeTxHash", "type": "bytes32"},
            {"name": "totp", "type": "uint256"},
        ],
    },
    "primaryType": "DeleteRequest",
    "domain": {
        "name": "Safe Transaction Service",
        "version": "1.0",
        "chainId": chain_id,
        "verifyingContract": safe_address,
    },
    "message": {
        "safeTxHash": safe_tx_hash,
        "totp": totp,
    },
}
```

# Endpoint
`DELETE` `multisig-txs/<safe-tx-hash>/`

# Body
```json
{
  "timestamp": "<integer unix epoch>"
  "signature": "<0x hex string>"
}
```

Superseeds #1737

**Comment by Uxio0** [comment]
@hectorgomezv @fmrsabino I already have a draft PR for this (without the event part), but you would need an event to detect the deletion, right? Or it would work?

**Comment by fmrsabino** [comment]
> @hectorgomezv @fmrsabino I already have a draft PR for this (without the event part), but you would need an event to detect the deletion, right? Or it would work?

We would need an event to be sent 👍

**Comment by Uxio0** [comment]
> > @hectorgomezv @fmrsabino I already have a draft PR for this (without the event part), but you would need an event to detect the deletion, right? Or it would work?
> 
> We would need an event to be sent 👍

Makes sense, it will be tackled in a different issue #1805

**Comment by katspaugh** [comment]
What's a totp, an OTP? Where do I get one?

**Comment by Uxio0** [comment]
It's documented on swagger: https://safe-transaction-mainnet.safe.global/
