### ISSUE TITLE
Remove price calculation from tx service

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1758]
# What is needed?
Price calculation must be removed from tx service.

- Token price endpoint must be removed
- Balances usd endpoint should set usd prices always to 0 as a first step, and then it should be removed

**Comment by moisses89** [comment]
@JagoFigueroa could you test if everything is ok? 
Token prices doesn't exist and balances with prices should works but returning price 0.

**Comment by JagoFigueroa** [comment]
Of course señor, I would never refuse :trollface: 

Checking! 😉

**Comment by JagoFigueroa** [comment]
All good for me. I will sync with the wallet QAs to see that everything is aligned with the new implementation for prices and mucho bueno 😉
