### ISSUE TITLE
[GET /balances/usd] - returns 0 for fiatConversion and fiatBalance

### ISSUE THREAD

**Issue by kryptocodes** [safe-global/safe-transaction-service#1759]
**Bug**
The transaction API routinely returns 0 balances (fiatConversion & fiatBalance) for all tokens when queries are made to retrieve the balance of a particular safe address in USD, even though the safe address does contain non-zero balances.

**To Reproduce**
- Make a GET request to the following endpoint:
https://safe-transaction-mainnet.safe.global/api/v1/safes/0x0DA0C3e52C977Ed3cBc641fF02DD271c3ED55aFe/balances/usd/?trusted=false&exclude_spam=false
- Check the response for token balances.

**Environment:**

Chain ID: 1 (Ethereum Mainnet)
Fiat Code: USD

**Expected behavior**
It supposed to return the fiatConversion and fiatBalance of the token 

**Additional notes**
The same requests made to the safe-client endpoint return accurate fiat balances & fiatConversion for the tokens at the specified safe address.

https://safe-client.safe.global/v1/chains/1/safes/0x0DA0C3e52C977Ed3cBc641fF02DD271c3ED55aFe/balances/usd?trusted=false

**Comment by moisses89** [comment]
@kryptocodes price calculation on transaction service will be discontinued. https://forum.safe.global/t/important-update-changes-to-token-pricing-in-our-api/4392 
Sorry about any inconvenience that this can cause.

**Comment by moisses89** [comment]
Just to clarify, safe-client-gateway still return prices from other sources. This only affects to the safe transaction service.
