### ISSUE TITLE
Send event when a Reorg happens

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1772]
# Background
It could be useful for some backends receiving tx service events to know when a reorg is detected on the chain

# Proposed structure
```json
{
  "type": "REORG_DETECTED",
  "blockNumber": "<integer>",
  "chainId": "<stringified-int>"
}
```

**Comment by moisses89** [comment]
@Uxio0 Should the event being published when the REORG is detected or the REORG is fixed? 
I could see several times that from REORG detected until fixed it takes time.

**Comment by Uxio0** [comment]
When Reorg is detected

**Comment by JagoFigueroa** [comment]
Tested and verified! Thanks for the help testing it 😄
