### ISSUE TITLE
Add examples for interacting with tx service on docs.safe.global

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1784]
Add examples for interacting with tx service on https://docs.safe.global/safe-core-api/service-architecture

- Creating a transaction and sending offchain signatures from the owners.
- Getting a transaction and executing it.
- Creating a message and sending offchain signatures.
- Getting last executed transaction.
- Batch Transactions (optional).
- Manage delegates.
- For documenting usage of the service we can give some alternatives:
    - https://github.com/safe-global/safe-eth-py/ (optional)
    - https://github.com/safe-global/safe-core-sdk (API Kit) (optional)
    - Simple curl calls

**Comment by Uxio0** [comment]
@falvaradorodriguez for this issue you can talk to @JagoFigueroa and check the Postman examples he has

**Comment by JagoFigueroa** [comment]
All good for me buenos señores 😄
