### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by alfredolopez80** [safe-global/safe-transaction-service#1812]
**Describe the bug**
th TX-indexer deployed in Kubernetes, with version 4.30.0

the indexer works, but send a lot errors: **_AttributeError_**
`2023-12-20 14:49:44,724 [ERROR] [???/???] pidbox command error: AttributeError("'NoneType' object has no attribute 'groups'")`
`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/kombu/pidbox.py", line 102, in dispatch`
    `reply = handle(method, arguments)
            ^^^^^^^^^^^^^^^^^^^^^^^^^`
  `File "/usr/local/lib/python3.11/site-packages/kombu/pidbox.py", line 124, in handle_cast
    return self.handle(method, arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
  `File "/usr/local/lib/python3.11/site-packages/kombu/pidbox.py", line 118, in handle
    return self.handlers[method](self.state, **arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
  `File "/usr/local/lib/python3.11/site-packages/celery/worker/control.py", line 340, in enable_events
    if dispatcher.groups and 'task' not in dispatcher.groups:
       ^^^^^^^^^^^^^^^^^`
`AttributeError: 'NoneType' object has no attribute 'groups'`

**To Reproduce**
 - Deploy tx-indexer with docker of this `image: safeglobal/safe-transaction-service:v4.28.4`

**Expected behavior**
Don't get this error into the workers pods

**Environment (please complete the following information):**
 - Staging
 - Which chain: Sepolia
 - OS: [Kubernetes/ Ubuntu]
 - Browser N/A
 - Version 4.30.0

**Additional context**
The indexing work but this error is recurrent and level up the process of workers, affect only worker pods (contracts, notifications and worker), th error is aroung Celery, but the setup is exactly of Docker imagen

**Comment by alfredolopez80** [comment]
i fixed add **'-E'** into the script for deploy workers:

Original command for celery:
`exec celery -C -A config.celery_app worker \
                --loglevel $log_level --pool=gevent \
                --concurrency=${TASK_CONCURRENCY} \
                --max-memory-per-child=${MAX_MEMORY_PER_CHILD} \
                --max-tasks-per-child=${MAX_TASKS_PER_CHILD} \
                --without-heartbeat --without-gossip \
                --without-mingle -Q "$WORKER_QUEUES"`

fix the error adding -E parameter
`exec celery -C -A config.celery_app worker \
                --loglevel $log_level --pool=gevent \
                --concurrency=${TASK_CONCURRENCY} \
                --max-memory-per-child=${MAX_MEMORY_PER_CHILD} \
                --max-tasks-per-child=${MAX_TASKS_PER_CHILD} \
                --without-heartbeat --without-gossip \
                --without-mingle` **-E** `-Q "$WORKER_QUEUES"`

**Comment by Uxio0** [comment]
`-E` should not be required and we don't see any issue with version `4.30.0` also deployed in kubernetes. Does it happen if you run the services locally? (try https://github.com/safe-global/safe-infrastructure)

**Comment by Uxio0** [comment]
We experienced the same error and added `-E` parameter, thanks for reporting it
