### ISSUE TITLE
Memory consumption higher from v4.29.0 in workers

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1819]
**Describe the bug**
Memory consumption from transaction services workers is increasing from v4.29.0. 

![image](https://github.com/safe-global/safe-transaction-service/assets/7888669/f2817963-32d6-4cd3-9108-b1724a8b54bc)

**Comment by Uxio0** [comment]
Could it be related to bumping Celery version on https://github.com/safe-global/safe-transaction-service/commit/d1f8b4d7853a71b73f9e71553188144247960fa6 ?

**Comment by moisses89** [comment]
> Could it be related to bumping Celery version on [d1f8b4d](https://github.com/safe-global/safe-transaction-service/commit/d1f8b4d7853a71b73f9e71553188144247960fa6) ?

Celery update was in [v4.30.0](https://github.com/safe-global/safe-transaction-service/releases/tag/v4.30.0) the issue started on 4.29.0

**Comment by Uxio0** [comment]
Good to know, thanks!

**Comment by moisses89** [comment]
After research the different commits on v4.29.0 we detect that the issue is related with Celery and non-root user.
The two commits related with root user was reverted to ensure that this is the reason. 
![image](https://github.com/safe-global/safe-transaction-service/assets/7888669/6d63a656-33eb-4b42-9d18-1f84b8aab333)
Taking a look of memory consumption of version v4.31.0 with the reverted commits we can conclude that the issue is in this two commits.
![image](https://github.com/safe-global/safe-transaction-service/assets/7888669/54181f59-57df-4a4b-9e0c-cad07aea4475)

**Comment by Uxio0** [comment]
@luarx do you think we can close this with the new version?
