### ISSUE TITLE
Filter historical txs by the token list

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-transaction-service#1836]
## Problem
We'd like to filter incoming and outgoing ERC20 transfers in the history based on a token list.

## Requirements
* Add a new query parameter for the history endpoint, e.g. `only-allowed-tokens=true|false`
* If the value is true, filter out transfers of tokens that aren't in the [allowlist](https://github.com/safe-global/token-list).
* If the value is false, do keep these transfers but mark them as untrusted with a new response field

**Comment by Uxio0** [comment]
Also specification should be updated to make it clear what you expect from the transaction service, as reading the initial message from @katspaugh we are merging `trusted` (transactions signed by at least one Safe owner) with scam transactions.

**Comment by katspaugh** [comment]
True, we shouldn't confuse the two flags. In the context of history though (which is what this is all about), executed transactions are always trusted in the signature sense, so it doesn't pose practical issues. But it would be good to rename the queue parameter to something more distinct.

**Comment by Uxio0** [comment]
Also, as I said, being this a transaction service service we should specify in the first message what's expected from the transaction, and not from the CGW. Otherwise your should move this ticket to the CGW and open a proper ticket on this repo

**Comment by Uxio0** [comment]
@katspaugh this requirement is still relevant?

**Comment by katspaugh** [comment]
Can be closed.
