### ISSUE TITLE
/v1/delegates/ hash to sign by a Safe owner is very scary and undescriptive

### ISSUE THREAD

**Issue by mjadach-iv** [safe-global/safe-transaction-service#1857]
# What is needed?
When you sign in a wallet a POST `/v1/delegates/` call to greate a new deleate, you are prompt with a request to sign a message that reads a hash like `0x132512f995866CcE1b0092384A6118EDaF4508Ff440771` which for 99% of users doesn't mean anything.

For a user comfort, the message that is being signed should look more like the actual POST of the call:
```
{
   message: "Add a delegate"
   safe: "0x232512f995866CcE1b009123A6118EDaF4508Ff"
   delegate: "0x132512f995866CcE1b0092384A6118EDaF4508Ff"
   epoch:1707297264
}
```

# Background
When using safe infrastructure, the developers would like to be as transparent to the users as possible, and the Wallet Popup like this one:
![image](https://github.com/safe-global/safe-transaction-service/assets/104129084/c5d7f1d6-4fbc-488d-be2c-c5689a319a2b)

does not shout confidance in the product.

## URL
`POST /api/v1/delegates/ `

**Comment by SCBuergel** [comment]
IMO this should be an [EIP712 compliant signature payload](https://github.com/safe-global/safe-transaction-service/issues/1857).

**Comment by Uxio0** [comment]
Agree, delegates have been here for a long time and that's why we went for a raw hash at that point. If you take a look for example at the signature for deleting a transaction it's already a EIP712, and we will do the same for delegates in the future

**Comment by Uxio0** [comment]
Superseeded by https://github.com/safe-global/safe-transaction-service/issues/1989
