### ISSUE TITLE
Counterfactual - Post endpoint to store Safe configuration

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1862]
# What is needed?
Store Safe Configuration for not deployed Safes.

# Endpoint
If applicable, description on the endpoint and the result you expect:

## URL
`POST /api/v1/counterfactual/safes/`

## Payload
TBD

## Response
`201 CREATED`

**Comment by AkintolaRichard** [comment]
Hello @Uxio0, I would love to help resolve this issue with your guidance.

**Comment by Uxio0** [comment]
Hi @AkintolaRichard , thank you very much but we don't require external help for this concrete issue 🙂

**Comment by AkintolaRichard** [comment]
Oh, thank you @Uxio0  for the clarification, perhaps in the nearest future if you have non concrete issue, I am available to help.

**Comment by Uxio0** [comment]
Waiting for @usame-algan feedback on what's needed to make this compatible with counterfactual deployment
