### ISSUE TITLE
Pagination for all-transactions does not work well

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1864]
https://safe-transaction-gnosis-chain.safe.global/api/v1/safes/0xeda046C9f8fd29636Bb621892718B9754F244b97/all-transactions/?limit=17&offset=0&executed=true&trusted=true does not return the number of elements set by `limit`. It looks like it's related to caching of the endpoint

**Comment by JagoFigueroa** [comment]
Looks good to me, I can see that the expected number of transactions are being returned now when setting a limit 😄
