### ISSUE TITLE
Improve flowchart for Safe Transaction Service

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1880]
# What is needed?
Currently we have a flowchart for the Safe Transaction service, we should extend it

This is the current diagram:
- https://docs.safe.global/api-service-architecture/safe-transaction-service#offchain-transaction-signatures
- https://github.com/safe-global/safe-docs/blob/main/pages/api-service-architecture/safe-transaction-service.mdx#L74

Diagram should be extended:

- Clarify that Alice and Bob are owners of a Safe with a `threshold=2`
- After transaction is created, a `multisig transaction created event` will be sent to RabbitMQ and to Firebase
- After user signs the transaction a confirmation is created,` a new confirmation event` will be sent to RabbitMQ and to Firebase
- After transaction is created and signed, Alice retrieves the transaction
- Transaction is sent to blockchain and executed:
  - A ERC20 contract is called, and funds are sent to the Zero Address
- Transaction service indexer picks the transaction from blockchain (scheduled task)
  - Missing data for the transaction is stored (like block, block hash, transaction hash, gas used...)
  - `A transaction executed event` is sent to RabbitMQ a Firebase

**Comment by JagoFigueroa** [comment]
Excelente trabajo señor! Looking good to me 🤝
