### ISSUE TITLE
Add expiry to transaction proposals

### ISSUE THREAD

**Issue by SKYBITDev3** [safe-global/safe-transaction-service#1923]
# What is needed?
Add expiry to transaction proposals.

# Background
The article [Why do I need to pay for cancelling a transaction?](https://help.safe.global/en/articles/40836-why-do-i-need-to-pay-for-cancelling-a-transaction) says that an on-chain transaction is required in order to cancel ("reject") a transaction proposal.

But if you add an expiry parameter then the proposal can automatically cancel if the transaction wasn't executed before the expiry date (which could be in a day, week, etc.).

The benefit would be that funds need not be wasted on an on-chain rejection transaction.

See [ERC20 permit](https://docs.openzeppelin.com/contracts/5.x/api/token/erc20#IERC20Permit-permit-address-address-uint256-uint256-uint8-bytes32-bytes32-
) which has a `deadline` parameter - the signature will no longer work after the date specified by deadline.

**Comment by SKYBITDev3** [comment]
Like `deadline` for ERC20 permit signatures, there could be an expiry date for each signature, after which the signature is no longer usable, so there's no risk of a signature being used any time in the future (the main concern exressed in the article) even though it's out there.

**Comment by Uxio0** [comment]
Adding a expiry field would require a change on the smart contract level and it's not a tx service feature. Currently there's a `DELETE` endpoint for removing proposed transactions in case you don't want to pay for a rejection transaction (which is safer)

**Comment by SKYBITDev3** [comment]
> Currently there's a `DELETE` endpoint for removing proposed transactions in case you don't want to pay for a rejection transaction (which is safer)

Why isn't that option available in the UI?

**Comment by Uxio0** [comment]
> Why isn't that option available in the UI?

Endpoint is very recent and they are working on it. If you need to use that feature you can use [Safe CLI](https://github.com/safe-global/safe-cli)
