### ISSUE TITLE
All-transactions cache can be broken due to deletion of transactions

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1931]
For caching `all-transactions`, count of database is used. Now we allow deletion of transactions, so it could be posible that a new transaction is added and other is deleted, so cache is not refreshed.

Some possible solutions:
- Add timestamp/identifier of last transaction (sorted by timestamp) to the cache
- Refresh cache when a transaction is inserted or deleted on database
- ...

**Comment by JagoFigueroa** [comment]
I have been playing around with the queue, deletion, replacement and transacting in general in dev and no issues for me. 

I will let my fellow QAs from the wallet team know later today in our sync to have an extra pair of eyes when they are testing on staging too in case they see something weird but it looks good to me.

Un saludito!
