### ISSUE TITLE
BUG-1

### ISSUE THREAD

**Issue by Phani1609** [safe-global/safe-transaction-service#1946]
Describe the bug:
There is unexpected behavior occurring within the service.

To Reproduce:

Perform a POST request on '...'
Provide the JSON payload you are submitting to the service (if applicable).
Followed by a GET request on '....'
If relevant, provide links to any related issues in other repositories.
Expected behavior:

Environment:

Is the issue observed in staging or production environment?
Which chain is the service interacting with?
Operating System: [e.g., iOS, Windows, Linux]
Browser (if applicable): [e.g., Chrome, Safari]
Version (if applicable): [e.g., 22]

**Comment by Uxio0** [comment]
Please provide a valid title and information about the response from the service
