### ISSUE TITLE
Check if ETHEREUM_4337_BUNDLER_URL uses the same chainId as ETHEREUM_NODE_URL 

### ISSUE THREAD

**Issue by luarx** [safe-global/safe-transaction-service#1987]
# What is needed?
It would be great to check if ETHEREUM_4337_BUNDLER_URL uses the same chainId as ETHEREUM_NODE_URL so that we can detect mistakes of using different chain_ids in the same service

In case that chainId is different, an option could be:
- Show an error log and do not start

**Comment by Uxio0** [comment]
Depends on https://github.com/safe-global/safe-eth-py/pull/899

**Comment by luarx** [comment]
https://github.com/safe-global/safe-eth-py/pull/899 has been completed 🙌 
So this can be scheduled to be implemented 🚀

**Comment by Uxio0** [comment]
@luarx PR is ready to review https://github.com/safe-global/safe-transaction-service/pull/2013
