### ISSUE TITLE
Refactor delegate endpoint signatures to use EIP712

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1989]
Currently we require to sign a hash, which is really wrong, and we should refactor the delegate signature to use an EIP712, similar to what we do for the delete transactions endpoint.

**Comment by mjadach-iv** [comment]
Duplicate of https://github.com/safe-global/safe-transaction-service/issues/1857#issuecomment-1934416322

**Comment by JagoFigueroa** [comment]
Looks good to me after checking with Felipe. I have left the checks for the v1 endpoints to the mobile team as a staging build of the app is needed to verify that delegation is working as expected.

Cheers
