### ISSUE TITLE
4337: Fix issues with reverted transactions

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#2035]
# What is needed?
Some transactions executed by Pimlico are reverted. We need to:
- Figure it out what's happening.
- Check if they are increasing nonce or not, in case they are increasing it we should index them.

# Related PRs
- https://github.com/safe-global/safe-transaction-service/pull/2040

**Comment by rmeissner** [comment]
Is the state of this issue correct? (It is open and a "Draft" on our GitHub project)

**Comment by Uxio0** [comment]
This was already fixed, but forgot to close it
