### ISSUE TITLE
Problem indexing events in Optimism

### ISSUE THREAD

**Issue by falvaradorodriguez** [safe-global/safe-transaction-service#2056]
The Safe Wallet team reported that in the response of the `multisig-transactions` [endpoint](https://safe-transaction-optimism.safe.global/api/v1/safes/0x71aC73a95f5b623ee70361BfA559F054Ddc06B6a/multisig-transactions/), the `confirmationsRequired` field was null.

After a first investigation no SafeStatus was found for the safe address. 

This was solved by executing a `reindex_master_copies` command.

It would be appropriate to investigate why this situation has been produced and take appropriate action if possible.

**Environment (please complete the following information):**
 PRO Optimism

**Additional context**
[Safe](https://app.safe.global/transactions/history?safe=oeth:0x71aC73a95f5b623ee70361BfA559F054Ddc06B6a) [Tx](https://optimistic.etherscan.io/tx/0xcd1c7d7f8a64a3b52d778c3f72d42447e81eec690f3903a27ffe25bb5e5b8f8e)

**Comment by Uxio0** [comment]
This should be fixed by https://github.com/safe-global/safe-transaction-service/pull/2095

**Comment by JagoFigueroa** [comment]
Hola amigos, will keep an eye on the chain for a few days transacting there for my testing. Moving this bad boy to my done column but will 👀
