### ISSUE TITLE
ABI submission for transaction data decoding 

### ISSUE THREAD

**Issue by 57Ark** [safe-global/safe-transaction-service#2057]
Hi, I want to submit contract abi for data decoding

Chain: Optimism (10)
Contract Address: 0x628539959F3B3bb0cFe2102dCaa659cf1E8D19EB

It's already verified on scanner (https://optimistic.etherscan.io/address/0x628539959F3B3bb0cFe2102dCaa659cf1E8D19EB#code)
and sourcify (https://sourcify.dev/#/lookup/0x628539959F3B3bb0cFe2102dCaa659cf1E8D19EB)

**Comment by Uxio0** [comment]
Then it will be picked by our service as soon as any account interact with the contract
