### ISSUE TITLE
4337: Add endpoint for adding more signatures to a safe-operation

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#2060]
# What is needed?
- Add more signatures to a `safe-operation`
- Similar flow to what we do with `multisig-transactions`

# Endpoint
## URL
`POST /api/v1/safe-operations/<safe-operation-hash>/confirmations/`

## Response
`201`

**Comment by JagoFigueroa** [comment]
It's on my radar, waiting for the implementation from the SDK team to test this 😄

**Comment by JagoFigueroa** [comment]
I will move this ticket to my "QA done" column and get back to it when the core sdk team implements this on their end. Originally the idea was to wait but seeing that this will be implemented next sprint this ticket will be more than archived by then. I will just create a QA ticket when I can test it 😄

**Comment by Uxio0** [comment]
Sounds good, thanks @JagoFigueroa !
