### ISSUE TITLE
ABI submission for transaction data decoding

### ISSUE THREAD

**Issue by 57Ark** [safe-global/safe-transaction-service#2066]
Hi, I want to submit 2 contracts' abis for data decoding

---

### RouterV3

Chain: Optimism (10)
Contract Address: 0x89f2E8F1c8d6D7cb276c81dd89128D08fc8E3363

It's already verified [on scanner](https://optimistic.etherscan.io/address/0x89f2E8F1c8d6D7cb276c81dd89128D08fc8E3363#code) and [sourcify](https://sourcify.dev/#/lookup/0x89f2E8F1c8d6D7cb276c81dd89128D08fc8E3363)
Also you can see [Safe interaction](https://app.safe.global/transactions/tx?safe=oeth:0x4cda5Fa96B5d436002175d958667C7EF3B644aA1&id=multisig_0x4cda5Fa96B5d436002175d958667C7EF3B644aA1_0x22bb22e202475bd26612e15fa6a8a178b97137d32318b3873da272628b621ad9) with this contract

But despite all that for some reason the contract is not decoding by Safe tx service

---

### Create2Factory

Chain: Optimism (10)
Contract Address: 0x95345a4d55daf6864924fc8861b311b9bc860e5f

It's alsoverified [on scanner](https://optimistic.etherscan.io/address/0x95345a4d55daf6864924fc8861b311b9bc860e5f#code) and [sourcify](https://sourcify.dev/#/lookup/0x95345a4d55daf6864924fc8861b311b9bc860e5f)

But here is a bit different situation, because Safe decodes this contract but only partially as you can see [here](https://app.safe.global/transactions/tx?safe=oeth:0x4cda5Fa96B5d436002175d958667C7EF3B644aA1&id=multisig_0x4cda5Fa96B5d436002175d958667C7EF3B644aA1_0xd4ac8a45a4516762f09dcb736ffaa38dddb1441680c9baa40ae18fd10e50a85a)
![image](https://github.com/safe-global/safe-transaction-service/assets/80775286/34ebb9bb-9cba-4bb4-97a4-aed65759b70b)

**Comment by Uxio0** [comment]
It should be picked automatically, but somehow it didn't work for this case. I did it manually, sorry for the delay
