### ISSUE TITLE
Messages: replace safeAppId with origin

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-transaction-service#2067]
# What is needed?
The message proposal endpoint atm takes a safeAppId as a way to identify from where the message comes. This has a few issues:
* It's not consistent with tx proposals which take an origin string (the URL of a dapp)
* If you delete the matching Safe App, this ID cannot be recreated, so all the messages are orphaned
* It doesn't convey any useful information for non-Safe App messages, i.e. for all WalletConnect-connected dapps
* Transaction service knows nothing about Safe Apps, so it's not applicable to non-wallet ecosystem participants

Hence I suggest to replace `safeAppId` with an arbitrary URL (we can call it also `origin`), so that we can show something useful to the user in the history.

> E.g. user connects to OpenSea and signs a message. We send a POST proposal with `"origin": "https://opensea.io/"`. Message history returns `https://opensea.io` in the `name` field of the Message list item.

# Endpoint
<img width="588" alt="Screenshot 2024-06-04 at 12 01 33" src="https://github.com/safe-global/safe-transaction-service/assets/381895/87231ddf-61d6-4cbb-bd63-8b922f916520">

# Timeline
Q3 or later

**Comment by Uxio0** [comment]
Is this still relevant @katspaugh ?

**Comment by katspaugh** [comment]
Yes. ✅

**Comment by thearbinaut** [comment]
Is this right

**Comment by Uxio0** [comment]
Ok, we will plan it @katspaugh

**Comment by thearbinaut** [comment]
Okay so what is needed and what is going on with the wallet address and private

**Comment by Uxio0** [comment]
@hectorgomezv @PooyaRaki @iamacook I guess this will impact you, right? How should we proceed?

**Comment by iamacook** [comment]
> @hectorgomezv @PooyaRaki @iamacook I guess this will impact you, right? How should we proceed? Should we maintain both fields for a while?

I'd suggest we maintain both and move to deprecate `safeAppId` once implemented client side.

**Comment by Uxio0** [comment]
Sounds fair @iamacook

**Comment by iamacook** [comment]
I've created [an issue to implement the above](https://github.com/safe-global/safe-client-gateway/issues/2048), and have subscribed to this issue to know when to make the change.

**Comment by Uxio0** [comment]
This PR is being deployed on `staging`

**Comment by iamacook** [comment]
> This PR is being deployed on `staging`

I've opened a [PR propagating the field to the Client Gateway](https://github.com/safe-global/safe-client-gateway).

**Comment by Uxio0** [comment]
Let us know if we can deploy this on production next week without breaking the cgw
