### ISSUE TITLE
Support v1.4.1 Safe Contracts on Avalanche C-Chain Transaction Service API

### ISSUE THREAD

**Issue by wongtsejian** [safe-global/safe-transaction-service#2070]
# What is needed?
Please support  v1.4.1 Safe Smart Contracts on Official Avalanche C-Chain Safe Transaction Service

# Background
Currently, the Official Avalanche C-Chain Safe Transaction Service only supports v1.3.0 Safe Smart Contract. However, other Official Safe Transaction Service (Ethereum Mainnet, Polygon Mainnet etc) supports v1.4.1 Safe Smart Contract. 

# Related issues
The v1.4.1 contracts were already deployed and PRs were raised to add them to safe-eth-py and safe-deployment repos. 

- pr for safe-eth-py has been merged: https://github.com/safe-global/safe-eth-py/pull/1048
- pr for safe-deployments has been merged: https://github.com/safe-global/safe-deployments/pull/536

# Endpoint
N.A.

## URL
N.A.

## Response
N.A.

**Comment by Uxio0** [comment]
Added in the last version just released
