### ISSUE TITLE
[Research] Make logging configurable

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#2173]
# Problem
When we need to see an issue in production, logging can only go from `INFO` or `WARNING` to `DEBUG`.

We need a way to increase the level for only a `Service` or `Task`

# Solution
Investigate about possible solutions, document them on this issue and open a new issue to implement the solution

# Initial ideas
- https://docs.djangoproject.com/en/5.0/howto/logging/#configure-responsive-logging and have some variables like `LOG_SAFE_INDEXING_LEVEL`, `LOG_PROCESSING_LEVEL`, `LOG_ERC20_INDEXING_LEVEL`

**Comment by moisses89** [comment]
@Uxio0 what do you think if even do it dinamically without need a service restart? I`m thinking in some action from django admin that enables the possibility to change the level for some Service or task.

**Comment by moisses89** [comment]
# Solution 1
Define logger by groups for example:
```
#ERC20_LOGGER
       "safe_transaction_service.history.indexers.erc20_events_indexer": {
            "level": env("ERC20_INDEXER_LEVEL", default="INFO")
        },
        "safe_transaction_service.history.tasks.index_erc20_events_task": {
            "level": env("ERC20_INDEXER_LEVEL", default="INFO")
        },
```
Where ERC20_INDEXER_LEVEL will define the log level for everything related with ERC20 indexer.

**Comment by moisses89** [comment]
Created an issue with the proposed solution. https://github.com/safe-global/safe-transaction-service/issues/2184
