### ISSUE TITLE
Optimize get balances endpoint

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#2177]
Getting the token addresses used by a Safe with a lot of erc20 transactions is so slow

**Comment by JagoFigueroa** [comment]
Hola! I have been checking a couple of safes with many balances and it has improved quite a bit! Uploading a couple of screenshots of the before and after for reference 😎 



![Image](https://github.com/user-attachments/assets/c22fb2c0-4406-4c9c-b471-6e413f0ef077)



![Image](https://github.com/user-attachments/assets/e4114435-21cd-4e5b-982b-e85b026a55b6)
