### ISSUE TITLE
Optimize  ´_process_decoded_element´

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#2181]
# What is needed?
With large number of events the decoded process is taking long times causing indexing delays. 
The main reason looks to be `_process_decoded_element`, then we should find out how to optimize this function.

**Comment by moisses89** [comment]
is_setup_indexed is consuming in some situations a few more time. 
In the next picture we can see that this is happening during `ProxyFactory` event decoding, that should happen after the `Setup` event. 
This two events are frequently indexed in a short time between them.
Creating a cache and storing that the `Setup` is indexed during the setup indexing, will avoid to hit database during `ProxyFactory` indexing. 
![image](https://github.com/user-attachments/assets/976c71f1-f15b-4801-886e-bcca8a07a3c5)

**Comment by JagoFigueroa** [comment]
tested and verified!
