### ISSUE TITLE
Research: all-transactions endpoint increases resource consumption

### ISSUE THREAD

**Issue by falvaradorodriguez** [safe-global/safe-transaction-service#2188]
After deploying version 5.7.0 of the service, the DevOps team commented that resource consumption increased.

Check if it comes from the all-transactions endpoint and reconsider the use of the cache.

**Comment by moisses89** [comment]
@JagoFigueroa to test this would be better create and execute transaction separately at least: 
- incoming and outgoing ether
- incoming and outgoing erc20
- incoming and outgoing erc721
- contract interactions

**Comment by JagoFigueroa** [comment]
Looking good to me. I have tried the mentioned cases in mainnet and polygon and haven't seen anything weird while creating and then executing 😄

**Comment by falvaradorodriguez** [comment]
I reopen the subject. It's necessary to research more to find the right solution.

**Comment by moisses89** [comment]
We saw that is a normal increment due the current requests.
Anyway we can reduce the memory consumption enabling compression https://github.com/safe-global/safe-transaction-service/issues/2199
