### ISSUE TITLE
Incorrect indexed transactions 

### ISSUE THREAD

**Issue by gershido** [safe-global/safe-transaction-service#2201]
**Describe the bug**
Transaction was successfully executed, but Arbitrum's transaction service shows that the proposal was cancelled. Instead, there's a new transaction that is shown as executed by the service, although it wasn't. This transaction also shows an incorrect owner address in one of the confirmations. 

**To Reproduce**
1. Do GET on https://safe-transaction-arbitrum.safe.global/api/v1/multisig-transactions/161EA0BDED794C84AFA87878DE4E8B45C3950989717E07AAEED4A41311AC41AD/
2. The result shows that this transaction wasn't executed, but here you can see the successful transaction with the same `safeTxHash`:
https://arbiscan.io/tx/0x06c36d4ebde377a96e0f5873ef8fa7e964b6d8afae860598257777954ef330bf#eventlog
<img width="740" alt="Screenshot 2024-09-02 at 23 15 44" src="https://github.com/user-attachments/assets/653437cc-77a3-448a-9690-6001d83a6ddf">

3. Do GET  on https://safe-transaction-arbitrum.safe.global/api/v1/multisig-transactions/0x5161f6d78a10a24b0ec43a8fa15df44830b537f42476653363f3ce6b59b901a2/
This `safeTxHash` is shown as executed, although it wasn't, and it includes an incorrect owner on its first confirmation.

**Expected behavior**
There should be only one executed `safeTxHash`, which is 161EA0BDED794C84AFA87878DE4E8B45C3950989717E07AAEED4A41311AC41AD, executed in transaction [0x06c36d4ebde377a96e0f5873ef8fa7e964b6d8afae860598257777954ef330bf](https://arbiscan.io/tx/0x06c36d4ebde377a96e0f5873ef8fa7e964b6d8afae860598257777954ef330bf) on Arbitrum.

**Environment (please complete the following information):**
 - production
 - Arbitrum
 - iOS
 - chrome

**Additional context**
Here are the respective transactions as shown in the Safe App:
1. https://app.safe.global/transactions/tx?safe=arb1:0x58Fab6d931B5a7C38B2E428D6cFEa7F071a1a225&id=multisig_0x58Fab6d931B5a7C38B2E428D6cFEa7F071a1a225_0x161ea0bded794c84afa87878de4e8b45c3950989717e07aaeed4a41311ac41ad
2. https://app.safe.global/transactions/tx?safe=arb1:0x58Fab6d931B5a7C38B2E428D6cFEa7F071a1a225&id=multisig_0x58Fab6d931B5a7C38B2E428D6cFEa7F071a1a225_0x5161f6d78a10a24b0ec43a8fa15df44830b537f42476653363f3ce6b59b901a2

**Comment by Uxio0** [comment]
Thanks for the detailed report. This should be fixed with the last version of the service we deployed yesterday. Please let us know if the bug still persists
