### ISSUE TITLE
Error 500 when calling estimate endpoint on sepolia

### ISSUE THREAD

**Issue by louis-md** [safe-global/safe-transaction-service#2203]
**Describe the bug**

When calling the `estimate` endpoint with the following data, the server runs into an internal error:

```curl
curl -X 'POST' \
  'https://safe-transaction-sepolia.safe.global/api/v1/safes/0x7AC3F72019a6dA4E7de65236bd756A97B53a64d4/multisig-transactions/estimations/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFToken: 5T4L6BGELuOMFYM2b34gzdALrVTqubkQj3glzJjKq1PuVYFq2AO9gCedFyDEKftv' \
  -d '{
"to":"0x7cbB62EaA69F79e6873cD1ecB2392971036cFAa4",
"value":0,
"data":"0x4c8c9ea10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a660566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ae3a0ac42e5ada9c557473e632374c9bb4a47ad8cf79dbe87566bfc4336c3ee164736f6c634300081400330000000000000000000000000000000000000000000000000000",
"operation":1,
"nonce":0
}'

```
**To Reproduce**
1. Do POST on 'v1/estimate' with above mentioned data

**Expected behavior**
No error or a meaningful error if the call fails.

**Environment (please complete the following information):**
 - Staging production? Production
 - Which chain? Sepolia
 - OS: [e.g. iOS] Any
 - Browser [e.g. chrome, safari] None
 - Version [e.g. 22] latest

**Additional context**

This error is linked with this stack exchange question: https://ethereum.stackexchange.com/questions/165768/getting-a-500-error-response-when-using-estimate-api-endpoint?noredirect=1#comment180122_165768

**Comment by Uxio0** [comment]
@JagoFigueroa Could you try to reproduce it? It's working for me

**Comment by JagoFigueroa** [comment]
Working for me too, will go ahead and close the issue. @louis-md please let us know if the issue still persists for you though 🙏
