### ISSUE TITLE
Contract not decoded on Arbitrum

### ISSUE THREAD

**Issue by iherger** [safe-global/safe-transaction-service#2205]
We have started using Safe on Arbitrum, and a few of our transactions are not properly decoded, even though the contracts are verified on Arbiscan.

Contracts: 
- https://arbiscan.io/address/0xa2B4c827dE13D4e9801eA1Ca837524a1A148Dec3
- https://arbiscan.io/address/0x2C6bef68DAbf0494bB5F727E63c8FB54f7D2c287

Is there anything we can do to get those ABI's pulled from Arbiscan?

**Comment by Uxio0** [comment]
Contracts are not indexed immediately, just checked and they are available
