### ISSUE TITLE
Some endpoints fail to return data for non-standard proxies

### ISSUE THREAD

**Issue by auryn-macmillan** [safe-global/safe-transaction-service#2223]
**Describe the bug**
When creating a safe with a non-standard proxy (created via something other than the safe proxy factory), some of the safe transaction services return errors for that safe. This renders the safe unusable in applications like the safe web wallet.

**To Reproduce**
1. Deploy any old proxy contract and point it to one of the safe mastercopies
2. Query that safe in the safe transaction service
3. Try to load it in the safe web wallet

Here's [one I baked earlier](https://app.safe.global/home?safe=sep:0x39a3CFCad4c434b0A06Cd3F0c0C1EBF1A0707EcF).

**Expected behavior**
The safe should behave like other safes, except where the proxy changes the default behaviour.

**Additional context**
For context, the proxy here is intended to give some account irrevocable module-like access to control the safe. This was a rushed implementation for the sake of testing, so there's a reasonable chance that the proxy I tested with is simply broken.

**Comment by Uxio0** [comment]
Hi @auryn-macmillan . This is expected. We need to check Proxy Singleton implementation to know the version of the Safe. We expect that to be on `slot 0`. 

We will work on supporting more proxies, but as a quick fix, you can put the Singleton address in the `slot 0` of your custom proxy, and it should work.: https://github.com/safe-global/safe-transaction-service/issues/2224

**Comment by Uxio0** [comment]
@auryn-macmillan we added support for [EIP-1167](https://eips.ethereum.org/EIPS/eip-1167) and [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967), but I see your proxy is still not working. The code is also not verified in Etherscan. What Proxy did you deploy?
