### ISSUE TITLE
L2: Support multiple Proxy deployments in the same transaction

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#2250]
Currently if there are more than one Proxy deployment in the same transaction they will not be decoded propertly.

There are some ways this can be done for proxies deployed using our official `ProxyFactory` :

- Check `ProxyCreation` events on the transaction and match the order with the list of decoded data.
- For `saltNonce` deployments calculate the deployment address using the decoded `saltNonce` and `initializer`.

**Comment by Uxio0** [comment]
@JagoFigueroa I created the test transaction on Sepolia as I didn't have funds on Polygon, but this should be tested on Polygon

**Comment by JagoFigueroa** [comment]
Tested and verified, thank you! I have created a couple of safes on polygon modifying your script a little bit and can confirm that all good 😄
