### ISSUE TITLE
Support transactions created via Gelato relay in `/creation` endpoint

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#2263]
Currently we don't show information about the Safe `creations` triggered by Gelato.

Example:

https://safe-transaction-polygon.safe.global/api/v1/safes/0x64D573869e60E541aBD72c4D0979aCD45427B944/creation/

We should decode the transaction as we did with the `Multisend` ones

**Comment by JagoFigueroa** [comment]
looking good to me 😄
