### ISSUE TITLE
Configure automatically trusted for delegates for signMessageLib 

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#2266]
# What is needed?
SignMessageLib should be enabled as trusted for delegates in every chain that the transactions service supports. 

# Background
Safe transaction service is able to configure the Safe contracts on startup. 
Would be necessary add this contract as Trusted for delegates in the `setup_contracts` command.

**Comment by JagoFigueroa** [comment]
Tested and verified!
