### ISSUE TITLE
Update API docs to use OAS 3

### ISSUE THREAD

**Issue by DefiDebauchery** [safe-global/safe-transaction-service#2268]
The Transaction Service's Swagger docs currently use v2 of the OpenAPI Specification, which doesn't work with some of the modern generative tools that only target OAS3. Upgrading will make the API easier to work with for local code generation (querystring filter classes, etc).

**Comment by Uxio0** [comment]
Thanks for the suggestion. It seems that we will have to migrate our dependency `drf-yasg`: https://drf-yasg.readthedocs.io/en/stable/readme.html#openapi-3-0-note
