### ISSUE TITLE
Balances really slow for one Safe in Base network

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#2283]
For https://safe-transaction-base.safe.global/api/v1/safes/0x32e52896663De88a65c2D94917b006404415A89f/balances/ is really slow (until cache is warm).

After debugging it, we realised is not an RPC or database optimization issue.

The issue is that for a lot of tokens they don't exist in the database so we try to recover them from blockchain, with no luck as they don't hold usual ERC20 information like `name` or `symbol`: https://basescan.org/address/0x20b09dCb0Ca884448acE9DDB10D7851Bfe26C261#readContract 

Method causing the bottleneck: https://github.com/safe-global/safe-transaction-service/blob/main/safe_transaction_service/history/services/balance_service.py#L293

**Comment by JagoFigueroa** [comment]
Tested and verified after our latest deployment. Cheers!
