### ISSUE TITLE
Allow Proposal Delete from Delegate that created it

### ISSUE THREAD

**Issue by DefiDebauchery** [safe-global/safe-transaction-service#2284]
In the API docs for `v1_multisig-transactions_delete`

> Only the proposer can delete the transaction.
> If the transaction was proposed by a delegate, the Safe owner who delegated to the delegate must be used.

Since we have the proposer via #1592, the Delegate that proposed a transaction should be permitted to delete it. This would allow for automated management -- we have Discord-based management of some tasks, and being able to undo a mistake without an explicit reject transaction (and without using the parent key!) would be helpful.

**Comment by Uxio0** [comment]
Your proposal makes a lot of sense, we will implement it

**Comment by JagoFigueroa** [comment]
Tested and verified 😄
