### ISSUE TITLE
Add Delegates events on creation/deletion/update

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-transaction-service#2299]
# What is needed?
Delegates _(proposers)_ is used on mobile clients only, and the traffic associated with the _delegates_ endpoint is low. However, after the delegates/proposers list is included in the Web UI, we expect a substantial increase in the traffic related to these endpoints.

The CGW strategy was not to cache the results for the delegates/proposers, but considering the traffic increase, it might make sense to add a caching/invalidation strategy. 

# Technical details
- Create a new event to signal the delegates/proposers' list has changed for a Safe address.
- Send the event to the general RabbitMQ, which is consumed by the CGW.

**Comment by JagoFigueroa** [comment]
How are the machines? 😎 tested and verified

<img width="1249" alt="Screenshot 2024-11-08 at 11 17 35" src="https://github.com/user-attachments/assets/8622ab63-f8f3-4f2c-9c59-81efbd157f1e">
Un saludito!
