### ISSUE TITLE
Safe-transaction avalanche - "KeyError: 'entrypoint'"

### ISSUE THREAD

**Issue by luarx** [safe-global/safe-transaction-service#2308]
**Describe the bug**
```
line 37, in from_bundler_response
    user_operation_receipt_response["entryPoint"],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'entryPoint'
```

**Comment by falvaradorodriguez** [comment]
This bug occurred when using Pimlico as a provider. It seems Pimlico api had a small bug and did not always return the `entryPoint` field. It has been clarified internally with Pimlico team, they have fixed it and [updated the api documentation](https://github.com/pimlicolabs/docs/commit/02a7967c31ebbd73e43658731482f294890fb0b5).

Please @luarx, let us know if the error persists
