### ISSUE TITLE
Pending Safe Operations support

### ISSUE THREAD

**Issue by yagopv** [safe-global/safe-transaction-service#2314]
# What is needed?
Allow to retrieve pending Safe Operations and paginate the result properly

# Background
The transaction endpoints allow us to retrieve pending transactions, but the new Safe Operations ones don't

# Endpoint
We are using the following endpoint:

`GET /safes/{address}/safe-operations`

In the case of the transaction endpoints we retrieve the pending ones by adding an `?executed=false` query string to the `safes/${address}/multisig-transactions` endpoint

## cURL
```
curl 'https://safe-transaction-sepolia.safe.global/api/v1/safes/0x72b57Bf71b17Ce3a1cB36a46a0fDE7BF945c9f33/safe-operations/'
```

**Comment by JagoFigueroa** [comment]
Tested and verified, many thanks!
