### ISSUE TITLE
confirmationsRequired always set to 1

### ISSUE THREAD

**Issue by molecula451** [safe-global/safe-transaction-service#2327]
Account threshold is 3, confirmationsRequired is always 1 when sending a transaction within the UI

![Screenshot from 2024-11-11 15-30-30](https://github.com/user-attachments/assets/c1db92c3-fe43-4c63-a4e3-ca776ff93cad)

**Comment by molecula451** [comment]
it looks like https://github.com/safe-global/safe-transaction-service/releases/tag/v5.10.0 prints correct confirmations but after that version it broke

**Comment by Uxio0** [comment]
@JagoFigueroa do you observe this behaviour?

**Comment by JagoFigueroa** [comment]
Hola friends! Not in prod at least. I have checked in a couple of chains to be sure and the confirmationsRequired is returning the expected number of confirmations. Are you running our infra locally? could you share your safe address and the chain that you are trying to transact in? I do not recognize that chain prefix 🤔
