### ISSUE TITLE
Request: Holesky Deployment

### ISSUE THREAD

**Issue by jbrower95** [safe-global/safe-transaction-service#2330]
# What is needed?
- Requesting a holesky deployment of Transaction service.

# Background
- Many staking teams use Holesky for experimenting with new staking features. I work for EigenLayer and we're currently working around this.
- There's a deployed [UI for Holesky](https://holesky-safe.protofire.io/welcome/accounts) but no one has deployed the transaction service yet, making it hard to test our automated integrations with Safe.
- This would be really helpful for us and other staking/restaking teams!

Thanks,
Justin

**Comment by protofivan** [comment]
Hey @jbrower95, this is Ivan from Protofire.

Transaction Service is deployed on Holesky and available at this link: https://transaction-holesky.holesky-safe.protofire.io

Feel free to reach out to me if you have any further questions.
