### ISSUE TITLE
Override bridged USDC token symbol to `USDC.e` in line with cultural norm

### ISSUE THREAD

**Issue by DefiDebauchery** [safe-global/safe-transaction-service#2344]
Similar to #1743, it would be helpful for bridged USDC tokens to be marked as such to prevent ambiguity. The established practice community-wide has been to rename the `symbol` to 'USDC.e' in displays, even though the symbol on-chain cannot change.

Polygon: [`0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174`](https://polygonscan.com/address/0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174)
Optimism: [`0x7F5c764cBc14f9669B88837ca1490cCa17c31607`](https://optimistic.etherscan.io/token/0x7f5c764cbc14f9669b88837ca1490cca17c31607)
Arbitrum: [`0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8`](https://arbiscan.io/token/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8)

This would make things easier from an automation side when using friendly labels through the `/api/v1/safes/{address}/balances/` API endpoint, but more importantly reduces confusion throughout the Safe UI, including the asset list, Transaction history, and confirmation screens where only the symbol is printed.

**Comment by Uxio0** [comment]
Done! Thanks for letting us know!

@JagoFigueroa could you check?

**Comment by JagoFigueroa** [comment]
Looking good, un saludito 😄

**Comment by DefiDebauchery** [comment]
Thanks so much! There is one last one that I didn't originally report, for zkSync - [`0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4`](https://explorer.zksync.io/address/0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4#contract#read-proxy)

vs https://safe-transaction-zksync.safe.global/api/v1/tokens/0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4/

Note that this token _did_ actually get updated to `USDC.e` canonically, since the contract is upgradeable. Dunno if that's something to consider for the token indexer.

**Comment by Uxio0** [comment]
Hi @DefiDebauchery , thanks for reporting! Our token indexer indexes once and never again, maybe that's something that we can do from time to time

**Comment by Uxio0** [comment]
Done for zksync too
