### ISSUE TITLE
Optimize calls to coingecko

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#311]
# Background
- Coingecko has a rate limitting, but multiple coin prices can be retrieved in the same call
- Code should be refactored to ask for multiple coins in the same request

**Comment by moisses89** [comment]
I would like to share that I successfully test that we could include 100 addresses in one request to `coingecko`.

**Comment by moisses89** [comment]
I think that we should know first if the token address is in coingecko or not to avoid requesting tokens that aren't going to receive price response.

**Comment by Uxio0** [comment]
Pricing features will be discontinued, so we will not work on this
