### ISSUE TITLE
Accept Ledger-style signatures to add delegates

### ISSUE THREAD

**Issue by philipcmonk** [safe-global/safe-transaction-service#353]
# What is needed?
While you can manually adjust Ledger's signatures to add delegates, they don't work out of the box.

# Background
I spent a while trying to add a delegate to a safe whose owners are all Ledgers before realizing that the reason my Metamask tests worked but the Ledger didn't, is that Ledger uses `v` of 0-4 while Metamask/MyCrypto/MyEtherWallet uses `v` of 27-30.  Should be able to support either case in one of these two places:
https://github.com/gnosis/safe-transaction-service/blob/edfaf01270c6a462ad091b5fdc5fd9720a52ed6b/safe_transaction_service/history/serializers.py#L301-L308

https://github.com/gnosis/gnosis-py/blob/8ffdfc3bc276934e3c3f1b24a3d206a1c3e33b96/gnosis/safe/signatures.py#L19

# Workaround
I took the signature from the Ledger and added 27 to the least significant byte.

**Comment by Uxio0** [comment]
Hi! Thanks, we are in the way of supporting external wallets so this will be very useful when integrating Ledger. We will keep you posted in this thread

**Comment by Uxio0** [comment]
Hi, this is not a priority for us. Why can't you adjust `v` before calling the API?

**Comment by Uxio0** [comment]
Hi, this is not currently a priority for us. Why can't you adjust `v` before calling the API?
