### ISSUE TITLE
Accurate price data for Superfluid Super Tokens

### ISSUE THREAD

**Issue by vmichalik** [safe-global/safe-transaction-service#772]
# What is needed?
Display Super Tokens with the price data of their underlying tokens. e.g. USDCx = USDC price, MATICx = MATIC price, as they are 1:1 exchangeable.

# Background
Currently, Superfluid Super Tokens display as 0 balances, but they are 1:1 wrappers around existing tokens with known prices. Super Tokens exist on Gnosis Chain, Polygon, Arbitrum and Optimism mainnets.

Some example Super Tokens:
Super Matic (MATICx) on Polygon https://polygonscan.com/token/0x3ad736904e9e65189c3000c7dd2c8ac8bb7cd4e3
Super USDC (USDCx) on Polygon
https://polygonscan.com/token/0xcaa7349cea390f89641fe306d93591f87595dc1f

More info on Super Tokens:
https://docs.superfluid.finance/superfluid/protocol-developers/guides/super-tokens

**Comment by trozler** [comment]
+1!
As someone who pays their employees through Gnosis SAFE in USDCx, this feature is much needed to ensure compatibility with current token accounting platforms e.g. Cointracker.

**Comment by Uxio0** [comment]
Hi,

We accept a PR for that if you want to implement it.

In the meantime, if you provide the most important Super Tokens and the token whose price we should take we can hardcode the price using other token as reference (please only the most important ones, as it's a manual process to add them)

**Comment by vmichalik** [comment]
Thanks @Uxio0, that would be amazing. Here are the primary tokens we need right now, but we'll look into making a PR for full Super Token support.

<google-sheets-html-origin><style type="text/css"></style>

Underlying Token | Coingecko | Super Token | Underlying Token Address | Super Token Address
-- | -- | -- | -- | --
MATIC | https://www.coingecko.com/en/coins/polygon | MATICx | n/a | https://polygonscan.com/token/0x3ad736904e9e65189c3000c7dd2c8ac8bb7cd4e3
ETH | https://www.coingecko.com/en/coins/ethereum | ETHx | n/a | n/a
USDC | https://www.coingecko.com/en/coins/usd-coin | USDCx | https://polygonscan.com/address/0x2791bca1f2de4661ed88a30c99a7a9449aa84174 | https://polygonscan.com/address/0xCAa7349CEA390F89641fe306D93591f87595dc1F
DAI | https://www.coingecko.com/en/coins/dai | DAIx | https://polygonscan.com/address/0x8f3cf7ad23cd3cadbd9735aff958023239c6a063 | https://polygonscan.com/address/0x1305F6B6Df9Dc47159D12Eb7aC2804d4A33173c2
wBTC | https://www.coingecko.com/en/coins/wrapped-bitcoin | wBTCx | https://polygonscan.com/address/0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6 | https://polygonscan.com/address/0x4086eBf75233e8492F1BCDa41C7f2A8288c2fB92
WETH | https://www.coingecko.com/en/coins/weth | WETHx | https://polygonscan.com/address/0x7ceb23fd6bc0add59e62ac25578270cff1b9f619 | https://polygonscan.com/token/0x27e1e4e6bc79d93032abef01025811b7e4727e85

**Comment by vmichalik** [comment]
In case I incorrectly copied any, there's a canonical list here: https://docs.superfluid.finance/superfluid/protocol-developers/networks

**Comment by Uxio0** [comment]
I added the prices for the tokens you provided, I'm closing the issue, if you want to work on a PR for an adapter for your token here you have examples: https://github.com/gnosis/gnosis-py/blob/master/gnosis/eth/oracles/oracles.py

**Comment by vmichalik** [comment]
thanks! much appreciated

**Comment by brymut** [comment]
Hi @Uxio0, may I ask what the next steps might be for getting the price data into the Gnosis Safe UI after this [PR/safe-global/safe-eth-py#381](https://github.com/safe-global/safe-eth-py/pull/381) ?

**Comment by Uxio0** [comment]
Hi, a new version of safe-eth-py must be released and the oracle must be added to the PriceService in safe-transaction-service

**Comment by brymut** [comment]
> Hi, a new version of safe-eth-py must be released and the oracle must be added to the PriceService in safe-transaction-service

Would this require any new follow up PRs on my end? Or is it relatively straight forward at this point?

**Comment by Uxio0** [comment]
I will follow up from here. I reopen the issue to keep track of this

**Comment by brymut** [comment]
May I ask if there's any update on this? May I lend a hand?

**Comment by brymut** [comment]
Hi @Uxio0, may I ask if there's any update on this?

**Comment by Uxio0** [comment]
It has just been merged and will be included in our next release (probably next week)
