### ISSUE TITLE
Create API to display SAFE circulating and fixed supply 

### ISSUE THREAD

**Issue by ennisjo** [safe-global/safe-transaction-service#800]
# What is needed?
An API that dynamically displays the Safe token's circulating supply and fixed supply.

# Background
To get the Safe token listed on apps such as Coinmarketcap and Coingecko, we need a simple API to derive both the circulating and fixed supply of SAFE tokens.

# Related issues
Take Cowswap's API as an example - https://api.cow.fi/token/circulating-supply

# Endpoint
circulating-supply
fixed-supply

# Urgency
We have the API ready at the end of May.

**Comment by Uxio0** [comment]
Makes sense John. I see this more for a new service than in the tx service, what do you think @safe-global/safe-services ?

**Comment by ennisjo** [comment]
Agree, welcome @safe-global/safe-services thoughts on the best repo to raise this issue.

**Comment by Uxio0** [comment]
Hi @ennisjo , we need more information for this issue:
- I wouldn't use any centralized platform to get the information if we can get that from blockchain.
- Most accurate and decentralzied solution would be querying the `Safe token` smart contract and subtract the `Safe tokens` owned by a subset of addresses that you should provide. Would this work?

**Comment by Uxio0** [comment]
Available at https://safe-supply.gnosis.io/v1/supply/
