### ISSUE TITLE
Transaction service rejects transactions signed by proper delegates

### ISSUE THREAD

**Issue by kx9x** [safe-global/safe-transaction-service#807]
**Describe the bug**
When POSTing against `https://safe-transaction.gnosis.io/api/v1/safes/0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52/multisig-transactions` with a transaction signed by a delegate with address 0x5E69fb460c9950F5AE90DafFc4C4F32EcafaCaA5, the Gnosis Safe Transaction service returns this reponse.

```
  ApiError: Error posting transaction: {"nonFieldErrors":["Sender=0x5E69fb460c9950F5AE90DafFc4C4F32EcafaCaA5 is not an owner or delegate. Current owners=['0x757280Bd46fC5B1C8b85628E800c443525Afc09b', '0x7321ED86B0Eb914b789D6A4CcBDd3bB10f367153', '0x6F2A8Ee9452ba7d336b3fba03caC27f7818AeAD6', '0x6E83d6f57012D74e0F131753f8B5Ab557824507D', '0x0Cec743b8CE4Ef8802cAc0e5df18a180ed8402A7', '0x74630370197b4c4795bFEeF6645ee14F8cf8997D', '0x99BC02c239025E431D5741cC1DbA8CE77fc51CE3', '0x48f2bd7513da5Bb9F7BfD54Ea37c41650Fd5f3a3', '0x7A1057E6e9093DA9C1D4C1D049609B6889fC4c67']. Delegates=set()"]}
```

**To Reproduce**
1. Do POST on https://safe-transaction.gnosis.io/api/v1/safes/0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52/multisig-transactions
  - Won't share the JSON since it has signed transaction data, but any valid transaction signed by the delegate is rejected.
  - 
**Expected behavior**
Since the [delegates endpoint](https://safe-transaction.mainnet.gnosis.io/api/v1/safes/0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52/delegates/) for this safe returns 3 delegates, we expect that 0x5E69fb460c9950F5AE90DafFc4C4F32EcafaCaA5 should be able to POST to the multisig-transactions endpoint with no problem.

The fact that the error shows `Delegates=set()` indicates a regression in the transaction service that makes it believe this safe has no delegates. Which is incorrect.

**Environment (please complete the following information):**
 - Production
 - Ethereum chain id 1

**Additional context**
This started happening a day ago. Before this we have been using this delegates for months and months without issue. Other safes my team owns do not have issues with delegates at this moment.

**Comment by Uxio0** [comment]
Hi @kx9x , we didn't do any change to the backend on the weekend, last one was on Thursday. It would be awesome if you can provide a signed transaction (if you want a simple one sending eth 1 wei from the Safe to the Safe) so we can try to reproduce

**Comment by Uxio0** [comment]
I have just tested and everything is working, can you try again?

**Comment by kx9x** [comment]
Still hitting the same exact issue

**Comment by kx9x** [comment]
@Uxio0 what's a good way to securely contact you with an example signed TX?

**Comment by kx9x** [comment]
Aight, it finally went through, I am going to chock this up as being a transient issue.

**Comment by Uxio0** [comment]
> hat's a good way to securely contact you with an example signed TX?

Remember that transactions are public once sent to the transaction service, so anyone could execute it. Make sure you only confirm transactions that you really want to execute

**Comment by kx9x** [comment]
> > hat's a good way to securely contact you with an example signed TX?
> 
> Remember that transactions are public once sent to the transaction service, so anyone could execute it. Make sure you only confirm transactions that you really want to execute

But the transaction service rejected the POST request? Are you saying the service still holds on to transactions that it rejects?

And what do you mean executable? If I shared a TX signed by a delegate, it wouldn't be executable until signed by a quorum of signers on the safe, right? 

Anyone could post it to the safe, but I don't think that means it is executable until quorum is reached.

**Comment by kx9x** [comment]
Like I understand that transactions that are successful posted to the safe and are signed by a quorum of signers are executable by anyone. Just not sure what you are trying to point out in this context of sharing one that cannot even get even be queued for signing in the first place.

**Comment by Uxio0** [comment]
> Like I understand that transactions that are successfully posted to the safe and are signed by a quorum of signers are executable by anyone.

Yes, that's what I meant, that's why I said there's no big harm in sharing the payload for a transaction here
