### ISSUE TITLE
OOM issue

### ISSUE THREAD

**Issue by AliakseiMalyshau** [safe-global/safe-transaction-service#813]
**Describe the bug**

Hello! We're running `safe-transaction-service` for Moonbase / Moonbeam / Moonriver networks and faced with issue OOM.

It started at January 25 - 26 and still continuing. Provided screenshot from Grafana:

![image](https://user-images.githubusercontent.com/91066845/166661248-2953d242-1153-448e-bc8d-f9638b4fcd6f.png)

Another screenshot for more detailed view:

![image](https://user-images.githubusercontent.com/91066845/166661303-cee69436-1175-4f10-9912-76a8f898dc29.png)

RAM memory always increase and service restart all the time

**To Reproduce**

Steps to reproduce the behaviour:

1. Start `safe-transaction-service`
2. Waiting 5 - 6 hours and watching how freeable memory is decreasing.
3. Service restarted

**Expected behavior**

I'm expecting OOM issue is absent and clear component work. Also I want to understand why this happening.

**Environment (please complete the following information):**

 - Staging and Production
 - Moonbase / Moonriver / Moonbeam
 - OS: Linux (AWS ECS service) 2 vCPU / 4 GB RAM
 - Browser: doesn't matter
 - Version: doesn't matter

**Additional context**

All comments added above.

Thanks!

**Comment by Uxio0** [comment]
Hi @AliakseiMalyshau,

You are not providing information about the version you are using, I expect you to be using the last release.

You should use more than 4GB of RAM. We rely heavily on caching (both local and redis) for providing quick results. You can try reducing the number of threads by setting the environment variable:

`WEB_CONCURRENCY=1`

Currently by default ``

https://docs.gunicorn.org/en/stable/settings.html#workers

**Comment by AliakseiMalyshau** [comment]
@Uxio0 thanks for the quick respond! Got it!
