### ISSUE TITLE
/safes/{address}/all-transactions/ ordering does not appear to be working

### ISSUE THREAD

**Issue by eranrund** [safe-global/safe-transaction-service#847]
**Describe the bug**
Hello!

It appears that the `ordering` query parameter is not working on the `/safes/{address}/all-transactions/` endpoint.
I have tried to use a few values, including `created`, `-created`, `nonce`, `-nonce`, etc, with the hope that one of them will let me go over the transaction list in a chronological order. It is possible [AllTransactionsListView](https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/views.py) is missing `ordering_fields`.

For context, I want to build something that syncs the list of transactions my gnosis safe had. Right now results are returned in reverse chronological order, making it difficult to efficiently use the `offset`/`limit` parameters to get transactions that appeared since the last one my script encountered. 

**To Reproduce**
1. Do GET on some `/safes/{address}/all-transactions/?ordering=created`, `/safes/{address}/all-transactions/?ordering=-created`, `/safes/{address}/all-transactions/?ordering=nonce`, etc - they all return results in the same order.

**Expected behavior**
The transaction list should be ordered based on the `ordering` query parameter.

**Environment (please complete the following information):**
 - Staging
 - Which chain? Rinkeby
 - OS: Irrelevant
 - Browser: FF
 - Version: Whatever is deployed on https://safe-transaction.rinkeby.gnosis.io/

**Additional context**
N/A

Thanks!

**Comment by rmeissner** [comment]
We should document what ordering is possible or remove it from swagger if no ordering is available
