### ISSUE TITLE
Wrong signer returned for safe tx

### ISSUE THREAD

**Issue by tschubotz** [safe-global/safe-transaction-service#858]
**Describe the bug**
Wrong signer returned for safe tx.

(I think this is a tx service issue, pls correct if wrong.)

**To Reproduce**

1. Check https://gnosis-safe.io/app/eth:0xBbA4C8eB57DF16c4CfAbe4e9A3Ab697A3e0C65D8/transactions/history
2. Go to tx history
3. tx with nonce 1238
4. It shows as signers an address that starts with 0x00.. 
![image](https://user-images.githubusercontent.com/1380529/170083518-411aee5e-4b3b-4f30-86ef-7f1096f97f76.png)

5. This address is not an owner of the Safe.
6. https://safe-transaction.gnosis.io/api/v1/multisig-transactions/0x67e2a0f1bfee089bd2978fcbb456a76ea62720a72aba5ce5327ac90a94a9f770/  returns the same data.
7. I checked the tx on [tenderly](https://dashboard.tenderly.co/tx/mainnet/0x805707593ed68ccb9d582216666729fedc7d32b3de3e949395be896437962bc3/debugger?trace=0.0.1.2)
8. If I'm not mistaken, the signature check does `ecrecover(dataHash, 27, 0x3c0f897cc8aec5caf54538e3a8b65c1353bb01158df8d1dea385eba2cfbbabaf, 0x2289abbfeadb3a16acda9d4889dd7acf8bcb334aa149db85a0c088561a611b0d)` with `dataHash= 0xf8e5f28b4e233dcd545e08ffd503cfc87d0cec269ad56d436a8555dec09655d4`
which results in `0xc8afb3e389c2693e588bb716d37cf1b53179506f` which is indeed an owner
-> I would expect this owner to be returned by the service and displayed in the UI

**Expected behavior**
Correct owner to be displayed

**Environment (please complete the following information):**
 - Staging or production? prod
 - Which chain? mainnet
 - OS: MacOS
 - Browser [e.g. chrome, safari]: Chrome

**Additional context**
-

**Comment by Uxio0** [comment]
This was related to https://github.com/safe-global/safe-transaction-service/issues/859 and it's fixed now
