### ISSUE TITLE
Safe nonce not up to date on tx service

### ISSUE THREAD

**Issue by tschubotz** [safe-global/safe-transaction-service#859]
**Describe the bug**
Safe nonce not up to date on tx service which prevents users from executing txs

**To Reproduce**

1. Go to tx queue of https://gnosis-safe.io/app/eth:0xBbA4C8eB57DF16c4CfAbe4e9A3Ab697A3e0C65D8/transactions/queue
2. Next tx has nonce 1239
3. Rejection tx cannot be executed (there are plenty failed txs on etherscan also, e.g. https://etherscan.io/tx/0xcaacf4c01acffb79b821d904364c410faff8bbdca1cdf19bfc41f0fb8d2e0490
4. Problem is that nonce of that Safe is already 1240: https://safe-transaction.gnosis.io/api/v1/safes/0xBbA4C8eB57DF16c4CfAbe4e9A3Ab697A3e0C65D8/

**Expected behavior**
All txs are indexed, users can execute txs (Or anyone since all confirmations are there)

**Environment (please complete the following information):**
 - Staging or production? prod
 - Which chain? mainnet
 - OS: [e.g. iOS] macos
 - Browser [e.g. chrome, safari] chrome

**Comment by Uxio0** [comment]
@tschubotz This is fixed. There was a missing tx from one year ago.

**Comment by Uxio0** [comment]
I'm closing the issues, feel free to reopen if you see something off

**Comment by tschubotz** [comment]
> This should be fixed now with the hotfix

When did the hotfix go live again? 
Was it this release? https://github.com/safe-global/safe-transaction-service/releases/tag/v4.3.3
