### ISSUE TITLE
Evaluate Nethermind for Gnosis Chain

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#868]
# What is needed?
As `OpenEthereum` was deprecated yesterday (more info on https://github.com/safe-global/safe-pm/issues/87) the only node supported on `Gnosis Chain` until the merge is `Nethermind`

# Background
- Tx service for Gnosis Chain is using `tracing` for indexing
- Nethermind should support tracing and must be fast enough to keep up with sync at least until *The Merge*

# Related issues
- https://github.com/safe-global/safe-pm/issues/87
- https://github.com/NethermindEth/nethermind/issues/4127#issue-1264465432

**Comment by svanegmond** [comment]
I would love to collaborate with you on improving support for Nethermind as this is what Shyft operates on, being a POA network.

Present issues I have.
1. While changing safe owners, the gas estimation functions incorrectly, in that the estimated gas is not sufficient. The web interface produces a helpful warning that the transaction may fail, and indeed it does, but doubling the gasLimit causes the transaction to succeed. The gas used was in fact below the estimated gas, so I don't know why I had to raise the limit.

2. Just recently, new transactions (send funds) are not seen by the tx gateway. I am still working this out.

```2022-07-20 16:50:38,102 [INFO] [92ad81d7/index_safe_events_task] Ignoring already processed event ApproveHash for Safe 0xeb7Dc17C09df5A7Afa6142C25ad5974117A4d27f on tx-hash=0x9e04a5feaddb4eac2a6a0524f993ad3e48705822926158f9a19c4d086f246d8a: duplicate key value violates unique constraint "history_internaltx_ethereum_tx_id_trace_address_c7c2fa9c_uniq"
DETAIL:  Key (ethereum_tx_id, trace_address)=(\x9e04a5feaddb4eac2a6a0524f993ad3e48705822926158f9a19c4d086f246d8a, 0) already exists.

postgres=# select * from history_internaltx where ethereum_tx_id = '\x9e04a5feaddb4eac2a6a0524f993ad3e48705822926158f9a19c4d086f246d8a';
-[ RECORD 1 ]----+-------------------------------------------------------------------
id               | 182
_from            | \xeb7dc17c09df5a7afa6142c25ad5974117a4d27f
gas              | 50000
data             | \x
to               | \x0000000000000000000000000000000000000000
value            | 0
gas_used         | 50000
contract_address | 
code             | 
output           | 
refund_address   | 
tx_type          | 0
call_type        | 1
trace_address    | 0
error            | 
ethereum_tx_id   | \x9e04a5feaddb4eac2a6a0524f993ad3e48705822926158f9a19c4d086f246d8a
block_number     | 6177141
timestamp        | 2022-07-20 16:50:20+00

postgres=# select * from history_internaltxdecoded where internal_tx_id =182;
-[ RECORD 1 ]--+---------------------------------------------------------------------------------------------------------------------------------------------
internal_tx_id | 182
function_name  | approveHash
arguments      | {"owner": "0x190deF14dAd5f856506C0Af7d7Ffdde78723f74e", "hashToApprove": "9f472d76ab742e632f788391e5bd6d8d052ee7a8c72b75a1364136b32c48667d"}
processed      | t

```

**Comment by Uxio0** [comment]
Hi @svanegmond , currently we are dealing with issues preventing us from migrating to Nethermind:

1. Regarding estimation, that's not something critical to us as we changed the way we estimate (from > 1.3.0 regular `eth_estimateGas` with `gasPrice=0`, `safeTxGas=0` and `baseGas=0` will work.
2. Regarding the not indexing stuff, that could be many things not related to Nethermind.

Please keep this issue only for discussing low level Ethereum RPC not working (like the issue we have with `trace_filter`) and not stuff like we don't see transfers in the indexer when Nethermind is configured. But for example "we see an error from the RPC when calling `eth_getLogs`" is very useful for us.

**Comment by Uxio0** [comment]
`trace_filter` is working now on an archive node using [v1.14.0](https://github.com/NethermindEth/nethermind/releases/tag/1.14.0). I will proceed to test to sync from scratch a transaction service

**Comment by Uxio0** [comment]
We are using Nethermind since last month with no issues
