### ISSUE TITLE
Should we prevent indexing proxies with not supported master copies

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#870]
# Background
Currently we are not doing anything for preventing indexing people with custom master copies or proxies, but we are getting support  questions about that, and it's not possible to provide support for custom implementations.

EDIT on 23/04/04: We are seeing a lot of issues in the indexer as it's trying to fix Safes that have a custom master copy and don't follow the logics implemented, so indexer is getting crazy. We should state that if a user "jumps" to a not supported master copy we will stop indexing the Safe forever. It's possible that we break people using "legit" master copies with some optimizations or custom use cases, but that's what modules are for.

# Current behaviour
Index everything that "looks" like our official Safes (matching events/traces)

# Proposed behaviour
We have 2 options:
- Keep as it is, but make really clear that we are not supporting custom proxies or master copies (that includes using not L2 master copies in L2 networks)
- Only index and support our official proxies/master copies

# Related issues
- #867

**Comment by mikhailxyz** [comment]
an example of such safe https://polygonscan.com/address/0xaC4E2D31D157bB9313F241c79dd41Ad833688E1E

**Comment by Uxio0** [comment]
Implemented a basic exclusion system on #1400
