### ISSUE TITLE
L2s don't reorg more often

### ISSUE THREAD

**Issue by InoMurko** [safe-global/safe-transaction-service#876]
**Describe the bug**
Maybe it's just the wording that's wrong or perhaps it makes sense to adjust the logic as well:
https://github.com/safe-global/safe-transaction-service/blob/master/config/settings/base.py#L392-L396

L2s that have shared security with the underlying L1 reorg only if L1 reorgs. With Optimisms Bedrock, this is implied directly because transactions are "attached" to L1 blocks.

Now I've seen this particular line was changed from 50 to 100 because of Polygon. Polygon is considered a side chain with it's own POS, so it makes sense to check reorgs. 
But if you wanted to check reorgs for L2, you should be looking at L1 blocks to be **safe-safe**.

**Expected behavior**
Monitor L1 blocks? Separate L2 for true L2s and sidechains?

**Additional context**
I guess the fix is simply to override this default value with something lower for true L2s or consider adjusting the logic to monitor L1 chain.

**Comment by Uxio0** [comment]
Hi @InoMurko, first I'm sorry as when I read this issue I wanted to take some time to answer it and then I forgot about it

You are completely right, we are wrongly using L2 naming for SideChains and L2 chains. But I would say at this point is not very worrying, as reorgs parameter is only used to check how many blocks to wait before marking a block as confirmed. This is something internal and blocks will keep showing, so indexing speed will not be affected, it's only that the service will be checking the not confirmed blocks from time to time. Doing a good adjustment can minimize queries to the node (not too much, as we are batching all and retrieving last blocks is a light operation), and we do based on the network (it's a environment variable and we adjust it on production).

Monitor L1 blocks for L2 chains sounds good, but currently we have never had an issue with this so we will not be working on this for now.

Either way, thank you very much for your suggestion and feel free to send us a PR if you have a proposal.
