### ISSUE TITLE
Inconsistent nonce value across different endpoints

### ISSUE THREAD

**Issue by fmrsabino** [safe-global/safe-transaction-service#878]
**Describe the bug**

The nonce seems to be inconsistent between different endpoints (when transactions are processed using `MultiSend`).

**To Reproduce**
1. GET https://safe-transaction.avalanche.gnosis.io/api/v1/safes/0xBFe691bF973ECf07cd03bC6e7B1E74DeA2DEF539/
3. Observe that nonce is `41`
4. For the same safe, get info about the transaction with nonce `43`: https://safe-transaction.avalanche.gnosis.io/api/v1/safes/0xBFe691bF973ECf07cd03bC6e7B1E74DeA2DEF539/multisig-transactions/?nonce=43
5. Observe that nonce was correctly executed and processed in the service

**Expected behavior**
Nonce should match with the latest successful transaction (`43`)

**Environment (please complete the following information):**
 - Staging or production? Production
 - Which chain? Avalanche
 - OS: [e.g. iOS] Non Applicable
 - Browser [e.g. chrome, safari] Non Applicable
 - Version [e.g. 22]: v4.3.2

**Additional context**

The following Ethereum transaction is tied to Gnosis Safe transaction from nonce `37` to nonce `43`

https://snowtrace.io/tx/0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b

**Comment by Uxio0** [comment]
I fixed it manually but there's indeed an issue on the indexer

**Comment by davide9800** [comment]
I'm one of the owner of that safe, how we can get out of this madness? Is 6 days that we can't so nothing

**Comment by Uxio0** [comment]
> 1. 0xBFe691bF973ECf07cd03bC6e7B1E74DeA2DEF539/

Could you try now?

**Comment by Uxio0** [comment]
> I'm one of the owner of that safe, how we can get out of this madness? Is 6 days that we can't so nothing

Could you try now?

**Comment by davide9800** [comment]
Fixed thanks

**Comment by davide9800** [comment]
Is stucked again...

**Comment by davide9800** [comment]
Is stuck again

**Comment by Uxio0** [comment]
I found the issue @safe-global/safe-services :
When sorting the pending transactions, we sort by `blockNumber`, `txIndex` and then `traceIndex`. Problem is that `traceIndex` is sorted as a string so this is the order for the transaction:

```
0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b 0 37
0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b 12 41
0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b 15 42
0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b 18 43
0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b 3 38
0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b 6 39
0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b 9 40
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 1 44
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 11 47
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 14 48
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 17 49
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 20 50
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 23 51
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 26 52
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 29 53
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 5 45
0xb510cf12dd8d55c4091534fcddb75a58f0dd92c373f49f48c3e4fddeecf366bc 8 46
```

@davide9800 We are giving top priority to this issue and we will release a hotfix asap

**Comment by Uxio0** [comment]
> Is stuck again

We deployed a hotfix, it should be working now
