### ISSUE TITLE
Endpoint for fetching safes with a given module enabled.

### ISSUE THREAD

**Issue by auryn-macmillan** [safe-global/safe-transaction-service#893]
# What is needed?
An endpoint to the transaction service that is similar to `/owners/{address}/safes/`, but is for modules, something like `/modules/{address}/safes/`. So that you can query for all of the safes that have enabled a given module.

# Background
There are many cases where a given module might be enabled on many safes. For example, some modules (like the spending limits module) are deployed as singletons to be used by many safes or a DAO framework might be enabled as a module to multiple safes it controls.

# Endpoint
Described above.

## URL
`GET /api/v1/modules/{address}/safes/`

## Response
```
{
  "safes": [
    "0xdead...beef",
    "0x1234...5678"
  ]
}
```

**Comment by dekanbro** [comment]
This would be very useful for us at Daohaus building on Zodiac. This would be for a use case where a DAO may have multiple treasury vaults, separated for organization or sand boxing. 

Being able to easily query all safes with the same module would help with a UI that lists all available 'vaults' for a DAO.

our initial exploration:
https://hackmd.io/@daohaus/HkmijuJY9
