### ISSUE TITLE
Duplicate txs returned

### ISSUE THREAD

**Issue by tschubotz** [safe-global/safe-transaction-service#895]
**Describe the bug**
Duplicate transactionsreturned

**To Reproduce**
1. Open https://gnosis-safe.io/app/eth:0xa4487e1abc196e80f35d0ce8639e97bcd96f3ea9/transactions/history
2. Check tx history

-> Seemslike txs are returned duplicated.

![image](https://user-images.githubusercontent.com/1380529/173200495-2c706228-0c38-49c1-b9b1-5ff4a952922d.png)

**Expected behavior**
All txs are there once

**Environment (please complete the following information):**
 - Staging or production? prod
 - Which chain? mainnet
 - OS: MacO
 - Browser Chrome

**Additional context**

https://safe-transaction.gnosis.io/api/v1/safes/0xa4487e1aBc196E80f35d0ce8639e97bCd96F3EA9/multisig-transactions/

**Comment by Uxio0** [comment]
It's the first time I see that. Maybe it's a really old bug as it's the first time I see that. I reprocessed the Safe and now it's fixed

**Comment by Uxio0** [comment]
We had the same info on staging, so that leads me to think it was a bug on the service long time ago

**Comment by moisses89** [comment]
I think that we should create an issue to track it.
