### ISSUE TITLE
Safe is created, but ownership API is not consistent

### ISSUE THREAD

**Issue by kx9x** [safe-global/safe-transaction-service#905]
**Describe the bug**
Safe ownership not syncing after safe creation.

**To Reproduce**
1. Do GET on https://safe-transaction.gnosis.io/api/v1/owners/0x1394E810AD8a67fB30277B07eB40472009875f36/safes/
  - {"safes":[]}
2. Then GET on https://safe-transaction.gnosis.io/api/v1/safes/0x500A2C0f765E3204ceCEBdA72621e0fAdd039537/creation/
 -  {"created":"2022-06-15T03:26:27Z","creator":"0x1394E810AD8a67fB30277B07eB40472009875f36","transactionHash":"0xa46daf0e04113f2cf293941ae3a44e4c2936a4ae27e60e7d89a939a6eb05952a","factoryAddress":"0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2","masterCopy":"0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552","setupData":"0xb63e800d00000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000001394e810ad8a67fb30277b07eb40472009875f3600000000000000000000000030b3d95e24ea00f5fb4b9bdf4f714159d9d793c2000000000000000000000000cf4f678b5c2051c97f2e02723bdd1158d35e1341000000000000000000000000b3e08599ac57666be68dbb3d311b9c607900a83b000000000000000000000000678252cd85e79d0022c6e8fcdb09cf3771ec1e890000000000000000000000000000000000000000000000000000000000000000","dataDecoded":{"method":"setup","parameters":[{"name":"_owners","type":"address[]","value":["0x1394E810AD8a67fB30277B07eB40472009875f36","0x30B3D95E24ea00F5Fb4b9bdf4f714159d9d793c2","0xCf4f678B5c2051C97f2e02723Bdd1158d35E1341","0xB3E08599AC57666BE68dBB3D311B9C607900A83b","0x678252Cd85e79d0022C6e8FcDB09cF3771ec1e89"]},{"name":"_threshold","type":"uint256","value":"4"},{"name":"to","type":"address","value":"0x0000000000000000000000000000000000000000"},{"name":"data","type":"bytes","value":"0x"},{"name":"fallbackHandler","type":"address","value":"0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4"},{"name":"paymentToken","type":"address","value":"0x0000000000000000000000000000000000000000"},{"name":"payment","type":"uint256","value":"0"},{"name":"paymentReceiver","type":"address","value":"0x0000000000000000000000000000000000000000"}]}}

**Expected behavior**
Since, the `/safes/0x500A2C0f765E3204ceCEBdA72621e0fAdd039537/creation` endpoint shows 0x1394E810AD8a67fB30277B07eB40472009875f36 as an owner, then the `/owners/0x1394E810AD8a67fB30277B07eB40472009875f36/safes/` endpoint should show 0x1394E810AD8a67fB30277B07eB40472009875f36 as an owner of 0x500A2C0f765E3204ceCEBdA72621e0fAdd039537.

However, it shows that 0x1394E810AD8a67fB30277B07eB40472009875f36 owns no safes.

**Environment (please complete the following information):**
 - production
 - ethereum mainnet

**Additional context**
I see lots of people creating multiple safes, likely because the Safe UI fails to load safes right after creation and folks keep retrying the TX.

**Comment by kx9x** [comment]
Aight, of course after I finally submit the issue, the endpoint works now.

It took almost 30 minutes to for the transaction service to correctly ingest the creation of my new safe though, which is concerning. It caused me to waste gas making another safe since I thought I did something wrong the first time.

**Comment by Uxio0** [comment]
> It took almost 30 minutes to for the transaction service to correctly ingest the creation of my new safe though, which is concerning. It caused me to waste gas making another safe since I thought I did something wrong the first time.

What do you mean? Did you try https://safe-transaction.gnosis.io/api/v1/safes/{safe_address}/ after creating the Safe?

> I see lots of people creating multiple safes, likely because the Safe UI fails to load safes right after creation and folks keep retrying the TX.

Lots of people? Can you provide more information? Are they using the API or are they creating them using the API or `safe-cli`?

**Comment by kx9x** [comment]
Yep, the safe wouldn't load on the UI at all. The left side tab that usually shows owned safes showed nothing for 30 minutes.

Also, the creation screen would spin a lot time after transaction confirmation and then eventually ask me to just retry despite the transaction confirming.

I check the TX history for safe creation on etherscan and saw plenty of history of EOAs making multiple safes within a few minutes of each other. At least for me this was because the first creation didn't show up quickly and UI prompted me to retry. I could imagine similar situations happened for others.

**Comment by kx9x** [comment]
https://etherscan.io/txs?a=0xa6b71e26c5e0845f74c812102ca7114b6a896ab2

Here is the TX history of creation.

And here is an example of someone making 2 safes within a minute of each other:
https://etherscan.io/tx/0x17fb578eb280822faca781d48f685747a96735db715f65461531f3b666b89eac
https://etherscan.io/tx/0x9a427f76fde3f5d5884bf6713c7ab24fbecc201f45594b3336fdba8b8aaa9922

Notice that the only difference between the calls are the saltNonce, so this might imply that the person created 2 safes with the same exact parameters because they thought they messed up the first.

There are many examples like this and could probably write a script to find out how often it is happening. Could be a useful stat to track between releases.

**Comment by rmeissner** [comment]
This has been refactored in the last months. As there is no further activity we will close this issue.
