### ISSUE TITLE
Networking issues when deploying services inside a VPN

### ISSUE THREAD

**Issue by the-amazing-ultraton** [safe-global/safe-transaction-service#928]
Hi,

With my team of Gnosis Guardians we are working to deploy safe infra on a new chain, but we're experiencing some issues related with the communication of safe-transaction-service and safe-config-service when those services are deployed behind a VPN.
None of this happens when we deployed these services with public endpoints (not inside a VPN).

As you know those components have a web service which providing a Swagger UI and Django Administrator UI console.
To expose "web" container, easy logging and handling errors we're using Nginx like reverse proxy (virtual server is running on 80 port) with specific nginx.conf and shared Nginx folder between "web" and "nginx" containers. 
In our infrastructure we use AWS ECS like environment to run BE and FE services and AWS Application Load Balancer to expose them in public. For Staging environment was decided to hide public URL endpoints for each BE and FE components to make them available via our private VPN.

We got 2 Issues

- We deployed safe-config-service and safe-transaction-service inside the VPN, but we've been experiencing an issue on the Swagger UI which is not supporting other option on the "Scheme" dropdown but "HTTP". 
Is there any way we could tell the config service to use HTTPs instead of HTTP

- safe-config-service expects an environment variable `CGW_URL` to reach the safe-client-gateway component, and safe-client-gateway has an variable called "config_service_uri". As I described above we hide public URL's in VPN network. Is it possible to use VPN-protected URL's with HTTP connection?

Thanks in advance for any help or guidance you could provide!

![image](https://user-images.githubusercontent.com/106994129/176276861-cab95b97-bd02-4444-afa4-81a7ce877b00.png)

**Comment by Uxio0** [comment]
Are you setting `HTTP_X_FORWARDED_PROTO` header to `https` in your reverse proxy? https://docs.djangoproject.com/en/dev/ref/settings/#secure-proxy-ssl-header
