### ISSUE TITLE
Data have not been decoded (verified contract / Optimism)

### ISSUE THREAD

**Issue by nkitlabs** [safe-global/safe-transaction-service#949]
Could you please help add the following ABI to the safe-UI on the Optimism chain? 

https://optimistic.etherscan.io/address/0x471d3dA2eB7D91149dA5e0dD4ce523267237380B#code

A contract is verified but data have not been decoded.
https://gnosis-safe.io/app/oeth:0xBCA3839a7fDeA4a008b6a115E1EFa4008eE85e5a/transactions/multisig_0xBCA3839a7fDeA4a008b6a115E1EFa4008eE85e5a_0x7c6b2b01f8980a89b0f0e746931e99d8dac9d11e21720f0bed63f552b986466f

**Comment by Uxio0** [comment]
Done, it will show up as soon as cache refreshes
