### ISSUE TITLE
Redis: Max Number of Clients Reached

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#951]
**Describe the bug**
- We are facing a `Redis: Max Number of Clients Reached` on the web instance of the transaction service
- Multiple endpoints seem to be affected (`all-transactions`, `balances`)
- Workers seem to be ok

**Expected behavior**
No issues

**Proposed solution**
- Add limit for the Redis Connection Pool and switch to `BlockingConnectionPool`: https://redis-py.readthedocs.io/en/stable/connections.html#connection-pools
- Add timeout for connections on the server and add `health-check`: https://github.com/redis/redis-py#connections . I don't think this will work.
- Increase number of connections on the server

**Additional context**
*Last 8 hours*
![image](https://user-images.githubusercontent.com/6909403/177972255-723cea4a-c221-4bf8-8eec-4500742612d1.png)

*Last week*
![image](https://user-images.githubusercontent.com/6909403/177972436-7f8b8c89-a0d2-4b74-a227-6185c1636cbb.png)

**Comment by luarx** [comment]
We are going to increment `redis maxclients` and check how it works

**Comment by Uxio0** [comment]
@luarx @moisses89 @fmrsabino Do you think we can close this for now?
