### ISSUE TITLE
CSRF cookie is not created if host != localhost

### ISSUE THREAD

**Issue by yod527** [safe-global/safe-transaction-service#970]
**Describe the bug**
I've been playing around with safe-infrastructure repository and met this issue https://github.com/safe-global/safe-infrastructure/issues/39

So, for localhost issue was fixed by switching browser.
But, when server is deployed somewhere, and address is not localhost, having the same issue with login, meanwhile safe config service is working fine.

Playing with CSRF_TRUSTED_ORIGINS variable does not help much, it looks to me like application is ignoring it...

**To Reproduce**
Deploy the service, and open /txs/admin interface, on address that differs from localhost.
You will notice, that cookie with name csrftoken even not created, and if you try to login, you will receive next error:
```
Forbidden (403)
CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for “same-origin” requests.
```

If you visit /cfg/admin interface in the same time, (of safe config service), csrftoken cookie is created immediately.

Next, when you try to open a /txs/admin interface one more time and login - you will face "unable to login" issue, which I have mentioned previously, without any errors. If I check application database, user which I use to login receives last_login timestamp, which probably means that auth was completed successfuly, so just /txs/admin interface does not show up, probably due to CSRF issue.

3. Links to issues in other repos (if possible)
https://github.com/safe-global/safe-infrastructure/issues/39
https://github.com/safe-global/safe-infrastructure/issues/21

**Expected behavior**
/txs/admin interface performs login correctly, on interfaces other than localhost

**Environment (please complete the following information):**
 - Matic
 - production
 - OS: MacOS 12.4
 - Browser Chrome 103.0.5060.134
 - Version safe transaction: 4.4.2

**Comment by Uxio0** [comment]
Hi @yod527 , for tx-service we have extra security in place. Cookies are possibly not appearing because there are configured as `secure` (only transmited by `https`)

**Comment by yod527** [comment]
@Uxio0 So, switching to https protocol may fix the issue?

**Comment by Uxio0** [comment]
Or just sending `HTTP_X_FORWARDED_PROTO=https` from nginx should be enough. We are preparing a PR refactoring the configuration: https://github.com/safe-global/safe-transaction-service/pull/974

**Comment by moisses89** [comment]
Hi @yod527 the PR mentioned was merged. Do you think that we could close this issue?
