### ISSUE TITLE
Batch Executed txns combine transfer data and are inaccurate

### ISSUE THREAD

**Issue by jasontheutopian** [safe-global/safe-transaction-service#971]
**Describe the bug**

For transactions that are "batch executed" together, the transfers data is incorrectly duplicated across all transactions in the batch.
For example, this safe batch executed Tx 102 (sending 0.1 LINK) and Tx 103 ( sending 0.001 USDC)

https://gnosis-safe.io/app/rin:0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d/transactions/history 

but in the data returned for those two transactions...

Tx 102 has transfers with TWO transfers. One being the 0.1 LINK and the other being the 0.001 USDC

Tx 103 ALSO has transfers with TWO transfers. One being the 0.1 LINK and the other being the 0.001 USDC

Even though they're supposed to be separate 

This is in safes/{}/all-transactions/ api

**To Reproduce**

1. Do POST on safes/{}/all-transactions/api with any safe that has batch executed txns. (i.e rinkeby 0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d)
2. Look at the transfer response. You will see duplicated data

**Expected behavior**

Transfers are distinct and related to each nonce. This way, we can accurately report Gnosis history.

**Additional context**

**Comment by Uxio0** [comment]
Please provide the problematic API url with the example. I don't see duplicated stuff: https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d/all-transactions/

**Comment by alextheutopian** [comment]
I just checked the response to that link and see the duplication:

```
 {
        "safe": "0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d",
        "to": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b",
       ...
        "nonce": 103,
      ...
        "transfers": [{
            "type": "ERC20_TRANSFER",
            "executionDate": "2022-07-15T04:19:16Z",
            "blockNumber": 11026678,
            "transactionHash": "0x1c46279db7a0b8c4d7314cda15bf42c68e2cb671981a243859cf1de5eed47fef",
            "to": "0x173572c72322872ed8dCF9B54722Cd9d177d4713",
            "value": "1000",
            "tokenId": null,
            "tokenAddress": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b",
            "tokenInfo": {
                "type": "ERC20",
                "address": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b",
                "name": "USD Coin",
                "symbol": "USDC",
                "decimals": 6,
                "logoUri": "https://safe-transaction-assets.gnosis-safe.io/tokens/logos/0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b.png"
            },
            "from": "0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d"
        }, {
            "type": "ERC20_TRANSFER",
            "executionDate": "2022-07-15T04:19:16Z",
            "blockNumber": 11026678,
            "transactionHash": "0x1c46279db7a0b8c4d7314cda15bf42c68e2cb671981a243859cf1de5eed47fef",
            "to": "0x173572c72322872ed8dCF9B54722Cd9d177d4713",
            "value": "100000000000000006",
            "tokenId": null,
            "tokenAddress": "0x01BE23585060835E02B77ef475b0Cc51aA1e0709",
            "tokenInfo": {
                "type": "ERC20",
                "address": "0x01BE23585060835E02B77ef475b0Cc51aA1e0709",
                "name": "ChainLink Token",
                "symbol": "LINK",
                "decimals": 18,
                "logoUri": "https://safe-transaction-assets.gnosis-safe.io/tokens/logos/0x01BE23585060835E02B77ef475b0Cc51aA1e0709.png"
            },
            "from": "0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d"
        }],
        "txType": "MULTISIG_TRANSACTION"
    }, {
        "safe": "0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d",
        "to": "0x01BE23585060835E02B77ef475b0Cc51aA1e0709",
        ...
        "nonce": 102,
        ...
        "transfers": [{
            "type": "ERC20_TRANSFER",
            "executionDate": "2022-07-15T04:19:16Z",
            "blockNumber": 11026678,
            "transactionHash": "0x1c46279db7a0b8c4d7314cda15bf42c68e2cb671981a243859cf1de5eed47fef",
            "to": "0x173572c72322872ed8dCF9B54722Cd9d177d4713",
            "value": "1000",
            "tokenId": null,
            "tokenAddress": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b",
            "tokenInfo": {
                "type": "ERC20",
                "address": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b",
                "name": "USD Coin",
                "symbol": "USDC",
                "decimals": 6,
                "logoUri": "https://safe-transaction-assets.gnosis-safe.io/tokens/logos/0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b.png"
            },
            "from": "0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d"
        }, {
            "type": "ERC20_TRANSFER",
            "executionDate": "2022-07-15T04:19:16Z",
            "blockNumber": 11026678,
            "transactionHash": "0x1c46279db7a0b8c4d7314cda15bf42c68e2cb671981a243859cf1de5eed47fef",
            "to": "0x173572c72322872ed8dCF9B54722Cd9d177d4713",
            "value": "100000000000000006",
            "tokenId": null,
            "tokenAddress": "0x01BE23585060835E02B77ef475b0Cc51aA1e0709",
            "tokenInfo": {
                "type": "ERC20",
                "address": "0x01BE23585060835E02B77ef475b0Cc51aA1e0709",
                "name": "ChainLink Token",
                "symbol": "LINK",
                "decimals": 18,
                "logoUri": "https://safe-transaction-assets.gnosis-safe.io/tokens/logos/0x01BE23585060835E02B77ef475b0Cc51aA1e0709.png"
            },
            "from": "0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d"
        }],
        "txType": "MULTISIG_TRANSACTION"
    }, 
```

As you can see, nonce 102 and nonce 103 have the same `transfers` array. Even though on the gnosis page (https://gnosis-safe.io/app/rin:0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d/transactions/history) the same transactions have different transfers.

TX Nonce 102 sent 0.1 LINK
Tx Nonce 103 sent 0.001 USDC

But in the response I attached, both are listed to have sent 0.1 LINK + 0.001 USDC

**Comment by Uxio0** [comment]
Hi @alextheutopian,

Thanks for the report, but this is expected. There's no way we can check where the events were emitted, we only know the `transactionHash`, so we show them in every transaction executed for that `transactionHash`

**Comment by alextheutopian** [comment]
So how does Gnosis distinguish the unique transfers in each transaction?

Because if you check the UI on the Gnosis Safe History page for that safe, it shows Tx Nonce 102 and Tx Nonce 103 with the proper unique transfers. (https://gnosis-safe.io/app/rin:0xbB63Cb79E8071de9F397808ECe48D6f8f5ae6d0d/transactions/history)

So technically the API is incorrect and doesn't seem to match the actual data from UI on Gnosis Safe.

We need to distinguish this for our application so would appreciate any help here :)

**Comment by Uxio0** [comment]
What you see in the UI is the decoded call to Transfer method (using transaction data), not the event ;)

**Comment by dragno-utopia** [comment]
Is the code that the UI uses to decoded data public? If so, could you please link it for us to take a look and borrow the logic?

**Comment by Uxio0** [comment]
Sure: https://github.com/safe-global/safe-react
