### ISSUE TITLE
Empty decoded data for contract interaction transactions in avalanche

### ISSUE THREAD

**Issue by pumpurum2** [safe-global/safe-transaction-service#994]
## Description
Empty decoded data for contract interaction transactions in avalanche
example: 0 and 1 in https://gnosis-safe.io/app/avax:0xe121c87B686Aa479a75709A9BcF7Fb1659c94B16/transactions/queue

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Avalanche

## Steps to reproduce
1. Go to safe in avalanche chain
2. create several transaction with app "Transaction builder" to contracts verified in sourcify.dev

## Expected result
Decoded transaction info

## Obtained result
raw transaction data

## Screenshots
![image](https://user-images.githubusercontent.com/93411443/182021423-fe7a95dc-7564-43c8-ac75-2387af628114.png)

**Comment by moisses89** [comment]
@pumpurum2 seems that this was fixed, could you close the issue or have you any more to add about the issue?

**Comment by pumpurum2** [comment]
yes, thanks! I created additional transactions direct to these contracts and it helps
